### ISSUE TITLE
Help loading weather meter.ini

### ISSUE THREAD

**Issue by cdeome** [SilverAzide/Gadgets#1]
Loading the weather meter.ini on other PC's works fine, but I have one that will not load for some reason, and I am not sure where to find the answer.  I was wondering if you had a chance to look this over.

When loading the ini.

Refreshing skin (Gadgets\Weather Meter\Weather Meter.ini)

Then the next line is:
Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S (Gadgets\Weather Meter\Weather Meter.ini - [@CurrentObservationDate])
Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S (Gadgets\Weather Meter\Weather Meter.ini - [@CurrentObservationTime])
Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S (Gadgets\Weather Meter\Weather Meter.ini - [@CurrentSunriseTime])
Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S (Gadgets\Weather Meter\Weather Meter.ini - [@CurrentSunriseTime])

I have more of the plugin in a word document.  But I was unsure what you needed.

Thanks for your time!  Best skins of all time!

**Comment by SilverAzide** [comment]
This is actually happening to many many people using skins that get data from weather.com. It is random, happening on some PCs but not others. Looks like there is a bad cookie in the IE cache (Rainmeter uses the Internet Explorer API built into Windows to make web calls.)

To fix this, go to your Control Panel and open Internet Options (or open IE and select Tools > Internet Options).  On the General tab in the history section, click the Delete button.  On the Delete Browsing History dialog, click AT LEAST the first 3 check boxes (the rest are up to you).  Click Delete to delete the items from the cache.

**Comment by cdeome** [comment]
You are awesome.. problem solved.. I wish I had paid closer attention to that.  Thanks again!!

Chris

**Comment by SilverAzide** [comment]
👍
