### ISSUE TITLE
Fan not showing on GPU Meter

### ISSUE THREAD

**Issue by Alex-Mirov** [SilverAzide/Gadgets#102]
Hello

For some reason the fan speed and % are not showing even when tweaking
with hwinfo64 settings.

I'm missing something?

Rainmeter: 4.5.18
hwinfo64: 8.02
Gadgets: 7.7.0

GPU : RTX 4080
Windows: 11

Please help!

Thanks

**Comment by SilverAzide** [comment]
The only way these would not show is if your configuration is incorrect or has changed.

Open the Settings and select the **List HWiNFO Indexes** option.  Then verify that your fan speed and usage sensors indexes as listed in the report are correctly set in the `HWiNFO.inc` variables file.  It is possible for sensor indexes to shift or change, especially if HWiNFO is updated, which would then affect your configuration.

**Comment by Alex-Mirov** [comment]
Hello

I've managed "List HWiNFO Indexes" from the start
and now the fans bars of rpm and precents are now showing!

It somehow got messed up!

Thanks
________________________________

**Comment by SilverAzide** [comment]
Glad you got it working!  I've noticed on a few rare occasions that after I upgrade HWiNFO, the sensor indexes may shift or be reordered.  This is especially true if you make several sensor changes and the index numbers are not sequential or have "holes" in the order.
