### ISSUE TITLE
Waether Meter not working

### ISSUE THREAD

**Issue by Sabbelchen** [SilverAzide/Gadgets#105]
Since a few days the Weather Meter is not working anymore. I tried to change the region and also restart the Widget, Rainmeter and my PC but nothing worked.

This is what I get the whole time in the log file.

DBUG (13:43:13.673) Gadgets\Weather Meter\Weather Meter.ini - [@LocationTimeZoneAbbreviation]: Fetching: Success!
DBUG (13:43:13.673) Gadgets\Weather Meter\Weather Meter.ini - [@LocationTimeZoneAbbreviation]: Parsing data...
ERRO (13:43:13.674) Gadgets\Weather Meter\Weather Meter.ini - [@LocationTimeZoneAbbreviation]: RegExp matching error (-1)
DBUG (13:43:13.674) Gadgets\Weather Meter\Weather Meter.ini - [@LocationTimeZoneAbbreviation]: Parsing data...done!
DBUG (13:43:13.679) Gadgets\Weather Meter\Weather Meter.ini - [@EntireSiteSuperParent]: Fetching: Success!
DBUG (13:43:13.679) Gadgets\Weather Meter\Weather Meter.ini - [@EntireSiteSuperParent]: Parsing data...
ERRO (13:43:13.681) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayDateString]: RegExp matching error (-1)
ERRO (13:43:13.682) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2DateString]: RegExp matching error (-1)
ERRO (13:43:13.683) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3DateString]: RegExp matching error (-1)
ERRO (13:43:13.684) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4DateString]: RegExp matching error (-1)
ERRO (13:43:13.685) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5DateString]: RegExp matching error (-1)
DBUG (13:43:13.687) Gadgets\Weather Meter\Weather Meter.ini - [@EntireSiteSuperParent]: Parsing data...done!

ERRO (13:43:16.641) Gadgets\Weather Meter\Weather Meter.ini - [@CurrentObservationDate]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.642) Gadgets\Weather Meter\Weather Meter.ini - [@CurrentObservationTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.642) Gadgets\Weather Meter\Weather Meter.ini - [@CurrentSunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.643) Gadgets\Weather Meter\Weather Meter.ini - [@CurrentSunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.643) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayDayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.643) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayMonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.644) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayMonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.644) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayDayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.645) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodaySunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.645) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodaySunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.646) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2DayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.646) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2MonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.646) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2MonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.647) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2DayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.647) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2SunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.648) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2SunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.648) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3DayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.648) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3MonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.649) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3MonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.649) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3DayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.650) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3SunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.650) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3SunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.650) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4DayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.651) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4MonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.651) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4MonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.651) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4DayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.652) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4SunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.652) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4SunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.653) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5DayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.653) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5MonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.653) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5MonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.654) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5DayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.654) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5SunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.655) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5SunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.656) Gadgets\Weather Meter\Weather Meter.ini - [MeasureCurrentObservationDate]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.656) Gadgets\Weather Meter\Weather Meter.ini - [MeasureCurrentObservationTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.852) Gadgets\Weather Meter\Weather Meter.ini - [@CurrentObservationDate]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.853) Gadgets\Weather Meter\Weather Meter.ini - [@CurrentObservationTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.853) Gadgets\Weather Meter\Weather Meter.ini - [@CurrentSunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.853) Gadgets\Weather Meter\Weather Meter.ini - [@CurrentSunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.854) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayDayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.854) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayMonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.855) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayMonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.855) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodayDayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.855) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodaySunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.856) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastTodaySunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.856) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2DayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.857) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2MonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.857) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2MonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.858) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2DayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.858) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2SunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.859) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay2SunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.859) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3DayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.859) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3MonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.860) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3MonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.860) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3DayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.860) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3SunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.860) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay3SunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.861) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4DayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.861) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4MonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.861) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4MonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.862) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4DayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.862) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4SunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.862) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay4SunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.863) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5DayShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.863) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5MonthLong]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.863) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5MonthShort]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.864) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5DayOfMonth]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.864) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5SunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.864) Gadgets\Weather Meter\Weather Meter.ini - [@ForecastDay5SunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.865) Gadgets\Weather Meter\Weather Meter.ini - [MeasureCurrentObservationDate]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (13:43:16.865) Gadgets\Weather Meter\Weather Meter.ini - [MeasureCurrentObservationTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S

Is it me or this a problem with weather.com?

**Comment by miquelfire** [comment]
Have you updated in the last few days?

**Comment by Sabbelchen** [comment]
Thanks. Updating the Gadgets worked. Thanks for the help!

And a big thank for your awesome work SilverAzide!
