### ISSUE TITLE
Strange system memory behavior in dual CPU system

### ISSUE THREAD

**Issue by candre23** [SilverAzide/Gadgets#108]
Found some more weirdness which may or may not be down to how windows reports things.

I have a dual CPU system with a total of 64GB RAM - 32GB per CPU.  Rainmeter reports this normally, "filling up" CPU0 first.  However, once the RAM for CPU0 is maxed out and it starts filling up CPU1's RAM, the numbers for CPU0 zero out like this.

![image](https://github.com/SilverAzide/Gadgets/assets/36796363/b59aceb7-415e-4d5d-8944-a183fbcdafee)

Then when it starts to back down, it will report RAM for both CPUs again, though if it's hovering around the full 64GB mark, both CPUs will occasionally zero out.

![image](https://github.com/SilverAzide/Gadgets/assets/36796363/10831e2c-62e7-4bc9-85c4-5fbfd0e37060)

I don't know how windows actually handles the reporting of memory usage in a dual CPU system like this.  My suspicion is that it's reporting slightly over 32GB per-CPU at times, and that's throwing rainmeter for a loop and causing it to display zeros.  If this is the case, could rainmeter perhaps assume that if the number is >100%, just display 100% instead of 0%?

**Comment by SilverAzide** [comment]
Thank you for the feedback!

I actually just made a ton of changes to the way memory is reported while I was fixing the other problem you reported.  There is a new feature that was added to the CPU Meter to show the memory composition (used, free, standby, etc.) and I needed to make extensive changes to handle machines running in NUMA mode like yours.  I stopped using the "old" Rainmeter way and added code to read the NUMA RAM data from the Performance Counters database.

Would you be willing to test a patch for me?  A Rainmeter patch will overwrite just a portion of your installation without affecting the rest.  So it will overwrite your CPU Meter(s) with a newer version, but should leave the rest of the skins intact.

**Comment by candre23** [comment]
Sure, I'll test it out.  Just let me know what I need to do.

**Comment by SilverAzide** [comment]
Hi @candre23, sorry for the delay in responding.

Please copy the attached .zip file to some location and change the file extension from `.zip` to `.rmskin`.  This is really an .rmskin skin installer file.  It is a "patch" installer, so it is going to simply overwrite the All CPU Meter skin files with newer versions.  You will lose your custom CPU Meter settings (if any), but they should easy enough to reset.

To minimize any possible issues I'd suggest the following:

- Unload all the CPU Meter skins first.
- Double-click the rmskin file and install it.
- When Rainmeter restarts, select the first (Node 0) All CPU Meter skin and let it reset itself for your hardware, then open the Node 1 skin for your other CPU.

Each CPU Meter should show the memory allocated to each NUMA node separately.  It should not show that strange behavior where one skin shows the RAM while the other other skin showed 0 bytes.

If you open the Settings, there is a new option under the RAM entry that reads `Show Memory Composition`.  IF you enable this, you will see the RAM bar now shows an additional shaded section which is the amount of RAM in standby mode (stuff that is cached, but can be freed when needed).  I'm very interested to know how it goes!

[All CPU Meter - Gadgets Patch_7.7.0.zip](https://github.com/user-attachments/files/16185588/All.CPU.Meter.-.Gadgets.Patch_7.7.0.zip)

**Comment by candre23** [comment]
It seems to have mostly worked.  The first upgrade attempt didn't seem to change anything, but I rebooted the machine, completely shut down rainmeter, ran it again, and that seems to have gotten it to take.  I'm seeing the shadow RAM usage now, and I don't see it zeroing out the usage when one side fills up, so that's great.

![image](https://github.com/user-attachments/assets/b8c06a37-14fe-4b4b-8b32-ac10fc7e2990)

I have enabled "show memory composition" in the settings, but I'm not getting that composition window popping up on mouseover.  That's the only part that isn't working as intended for me.

**Comment by SilverAzide** [comment]
Oops!  My bad!  Looks like I goofed up the logic that shows the memory composition tooltip.  I'll fix that.

**Comment by SilverAzide** [comment]
@candre23,
Unzip the attached file and copy over the existing `CpuMain.inc` file in your `Rainmeter\Skins\Gadgets\All CPU Meter` folder with this new version.  Then refresh your two CPU Meters (no need to restart Rainmeter, reboot, or etc.).  This should correct the tooltip problem.

[CpuMain.zip](https://github.com/user-attachments/files/16228157/CpuMain.zip)

**Comment by candre23** [comment]
That seems to have done the trick.  Thanks!

**Comment by SilverAzide** [comment]
Corrected in next release.  Thanks!
