### ISSUE TITLE
GPU Meter not detecting HWiNFO

### ISSUE THREAD

**Issue by amitai45** [SilverAzide/Gadgets#11]
As shown on the screenshot, I've been trying to get it to notice HWiNFO when it's running and was making sure detection settings on the app are checked off and everything, but I can't get this skin to display by GPU stats.

This is my first ever github post so if there's anything I need to add please let me know.

![DELETE](https://user-images.githubusercontent.com/71159006/102029383-536fb180-3d7c-11eb-9717-60e78bcc87c6.jpg)

**Comment by SilverAzide** [comment]
From your screenshot, it looks like you did not configure the HWiNFO settings for your GPU, or if you did, they are not quite right.  Make sure you follow the instructions [**here**](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Configure-the-GPU-Meter#how-to-configure-the-gpu-meter) and especially the instructions in the HWiNFO.inc file.

Please note that on some machines, the GPU you want to monitor is not the first one in the list (starting with #0).  For example, most Intel machines have 2 GPUs, a built-in Intel GPU plus a dedicated graphics card.  The Intel GPU is usually  GPU #0, and the dedicated card is usually GPU #1.  So make sure you configure the proper one AND use the proper GPU Meter.  HWiNFO will indicate your GPU numbers.  As a tip, I recommend configuring all three GPU Meters using your dedicated card's sensor IDs, so it won't matter which GPU Meter you use, they will all show the same data.

Also, if you have a machine with only the built-in Intel GPU, you will not be able to monitor much, as there are very few sensors available.

Let me know if you have any questions or are able to resolve this issue.

**Comment by amitai45** [comment]
I thought those instructions didn't exist cuz I couldn't find them in the readme. Thank you for directing me to them. I was able to connect the sensors to the skin.

**Comment by SilverAzide** [comment]
OK, great!  Glad you got it working.  The help topics are accessible by clicking the little "?" symbols in the Settings.  Some are just tooltips, but ones you can click will take you to various wiki articles if you want more info.
