### ISSUE TITLE
Glass is not resizing in analog clock

### ISSUE THREAD

**Issue by giquo** [SilverAzide/Gadgets#110]
![glass-resize](https://github.com/user-attachments/assets/c2d45caf-8219-47bb-87b4-bc15f01ef331)

As the picture suggest, I put 0.9 in size but the glass seems to keep occupying 100%

**Comment by SilverAzide** [comment]
Whoops!  Thanks for catching this bug.  I will fix this in the next version of the Gadgets.

In the meantime, you can fix this quite easily yourself.

- Right-click the skin and select **Edit skin** from the context menu.
- Scroll to the bottom of the file and find the `[MeterGlass]` line.
- Add the `TransformationMatrix` line to the meter, as shown here:

```ini
[MeterGlass]
Meter=Image
ImageName="#@#Clock\#ClockStyle#Glass.png"
X=0
Y=0
Hidden=#HideHighlights#
TransformationMatrix=#Scale#;0;0;#Scale#;#Scale#;#Scale#
```

Refresh the skin and you should be set.  Thanks!

**Comment by giquo** [comment]
HEHEEEEY!!! nice and tidy
Thanks!!!
That clock from vista definetly looks more fancy with glass!

**Comment by SilverAzide** [comment]
Fixed in next release.
