### ISSUE TITLE
Hyper-V Monitor

### ISSUE THREAD

**Issue by lispeedyg** [SilverAzide/Gadgets#115]
Hi all,
I love the gadgets here.  They help me get an excellent view of the system at any given time.

I was wondering if it would be possible to include Hyper-V Monitor Gadget that was last updated in 2013ish time frame.  It is an indispensable tool for me as I manage quite a few Hosts/VM's.  I'd be happy to help support this if you folks agree. to take this on

Please let me know,
Thanks, Gus

**Comment by SilverAzide** [comment]
Hello!  Glad to hear you are enjoying the Gadgets!

Are you referring to this Sidebar Gadget?
![this](https://markswinkels.nl/wp-content/uploads/2008/11/hyper-v_sb_01.jpg)

If so, I scanned the code quickly and it requires a LOT of WMI queries to function, as far as I can tell.  Perhaps some functionality could be done with Windows Performance Counters, which has an extensive set of Hyper-V counters and -- most importantly -- which Rainmeter can access natively, but the only way to do WMI queries is create a plugin.

Someone saved the code on GitHub (https://github.com/WaldenL/hyper-v-gadget), but whatever docs that were done are lost.  The CodePlex site and the author's home page are all dead, looks like.  Do you know if any docs that describe what it did still exist?

It seems unlikely that I would want to tackle a task as large as this, unless the functionality is easy to implement and doesn't require a plugin.  I'm not a system admin so I don't have a lot of experience with Hyper-V other than running a few local VMs for WSL and WSA.

**Comment by SilverAzide** [comment]
No response from OP.  No plans to do this at this time.
