### ISSUE TITLE
CPU Gadget no longer showing Clock speed if HWiNFO is running.

### ISSUE THREAD

**Issue by DIGIN4** [SilverAzide/Gadgets#12]
Using latest stable version of HWiNFO and gadgets.
CPU: AMD Ryzen 7 3700X

**Comment by SilverAzide** [comment]
It's working fine for me with HWiNFO 6.40.4330.  If you recently upgraded to this version, you might want to double-check your HWiNFO sensor and entry IDs.  Sometimes the IDs change when HWiNFO is updated.  It's happened to me several times.
