### ISSUE TITLE
CPU name string too long (11th gen )

### ISSUE THREAD

**Issue by zme-ul** [SilverAzide/Gadgets#16]
the 11th gen CPU names is way to long to fit in the window of **All CPU Meter**
I manually edited the config file to `Substitute="\(R\)":"","\(TM\)":"","\(tm\)":"","Intel ":"","AMD ":"","CPU ":"","@.*":"","\s$":"","11th":"","Gen":""`
so it now displays **Core i7-11700K** instead of **11th Gen Core i7-11700K**

**Comment by SilverAzide** [comment]
Ugh, Intel changed the format yet again?!  🤬  Can you tell me the full name of your CPU?  The simplest way is at a command prompt or PowerShell prompt, enter the command:

`wmic cpu Get Name`

Thank you for reporting!

**Comment by SilverAzide** [comment]
This fix will be included in the next release of the Gadgets.  This fix for Intel CPUs will also include numerous fixes for AMD CPUs.  The Gadgets release is planned for as soon as HWiNFO releases 7.02 for production use, so it should be soon (I hope).
