### ISSUE TITLE
All CPU Meter - page %

### ISSUE THREAD

**Issue by dougsmucker** [SilverAzide/Gadgets#17]
Thank you for maintaining and updating this skin.

In "All CPU Meter" the Page % displays as 0% when it should be 6%.  I believe you missed the "Percentual=1" when you updated this gadget. I added it and everything looks good.
```ini
[MeterPercentPage]
Meter=String
MeterStyle=StyleTextBarPercent
MeasureName=CalcPagePercentUsage
FontColor=#BarColorPage#
Y=(12 * ((#HidePage# + 1) % 2))r
Percentual=1
Hidden=#HidePage#
```

**Comment by SilverAzide** [comment]
Dang!  I'll fix it and repost the .rmskin.  The fan percentage is wrong too.  Great catch and thanks a bunch for the feedback!

**Comment by SilverAzide** [comment]
Fixed and skins updated!  You get a gold medal for saving the day.  🎖️ 😉
