### ISSUE TITLE
Weather Meter ...connecting

### ISSUE THREAD

**Issue by evlyxx** [SilverAzide/Gadgets#2]
Weather Meter has stopped working today just permanently connecting tried several methods of identifying my location and multiple locations. Have the  Weather Channel blocked stuff again?
![2020-06-04_165924](https://user-images.githubusercontent.com/66432036/83780234-d1902480-a684-11ea-88fd-6ae760c7e24f.png)
![2020-06-04_165641](https://user-images.githubusercontent.com/66432036/83780239-d48b1500-a684-11ea-87e4-909f94547bd0.png)
![2020-06-04_165615](https://user-images.githubusercontent.com/66432036/83780254-d81e9c00-a684-11ea-8ef7-fac22102d01d.png)

**Comment by cdeome** [comment]
You are correct. Mine too.  Did weather.com change their API?

CD

**Comment by DanaMW** [comment]
This is what I have in the log and weather does not display, Thanks for looking at us.

ERRO (16:56:11.613) Gadgets\Weather Meter\Weather Meter.ini -
 [@CurrentObservationDate]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:11.614) Gadgets\Weather Meter\Weather Meter.ini -
 [@CurrentObservationTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:11.614) Gadgets\Weather Meter\Weather Meter.ini -
 [@CurrentSunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:11.615) Gadgets\Weather Meter\Weather Meter.ini -
 [@CurrentSunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:11.619) Gadgets\Weather Meter\Weather Meter.ini -
 [MeasureCurrentObservationDate]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:11.619) Gadgets\Weather Meter\Weather Meter.ini -
 [MeasureCurrentObservationTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:12.618) Gadgets\Weather Meter\Weather Meter.ini -
 [@CurrentObservationDate]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:12.619) Gadgets\Weather Meter\Weather Meter.ini -
 [@CurrentObservationTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:12.620) Gadgets\Weather Meter\Weather Meter.ini -
 [@CurrentSunriseTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:12.621) Gadgets\Weather Meter\Weather Meter.ini -
 [@CurrentSunsetTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:12.624) Gadgets\Weather Meter\Weather Meter.ini -
 [MeasureCurrentObservationDate]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S
ERRO (16:56:12.624) Gadgets\Weather Meter\Weather Meter.ini -
 [MeasureCurrentObservationTime]: Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S

**Comment by SilverAzide** [comment]
Hi all!  Yes, as you have suspected, weather.com pulled the trigger on their new "V3" data format on their site yesterday and broke all the TWC-based weather skins.  AGAIN.  They have been testing this for a couple weeks (affecting some people and not others), and it looks like yesterday they rolled it out world-wide.

I will have a new version of the Gadgets with this issue in the next day or two.  I'm still testing, but all looks good and the new version will have 100% of the functionality of the old one.

Hang in there for just a little longer!  :)

**Comment by evlyxx** [comment]
Thanks for the swift reply, if you need any alpha/beta testers I'm happy to test

**Comment by SilverAzide** [comment]
Fixed!  See v5.4.1 **[here](https://github.com/SilverAzide/Gadgets/releases)**.

**Comment by DanaMW** [comment]
Thanks.

**Comment by evlyxx** [comment]
Thanks, working like a charm
