### ISSUE TITLE
CPU meter not showing AMD 2700X performance/percent usage

### ISSUE THREAD

**Issue by JAG836** [SilverAzide/Gadgets#21]
Hello,

Since upgrading to HWiNFO 7.0X, the CPU meter has not been showing performance/usage information for my 2700X and I can't figure out why. 
## What I've tried so far
1. Uninstall/reinstall HWiNFO, Rainmeter, Gadgets
2. Use different sensors. E.g. Core Clock vs Core Effective Clock
3. Use legacy mode
4. Shared memory = on
## Versions
**HWiNFO64:** 7.02-4430
**Rainmeter:** 4.4.0.3347 (beta, 64 bit)
**Gadgets:** 6.0.2
Win 10 home, version 20H2, build 19042.928
## Rainmeter log
The Rainmeter log will show the following lines over and over again:
```
DBUG (13:15:37.040) Gadgets\All CPU Meter\All CPU Meter.ini - [MeasureCPUPercentPerformance]: Could not find a category called Processor Information
DBUG (13:15:37.283) Gadgets\All CPU Meter\All CPU Meter.ini - [MeasurePagePercentUsage]: Could not find a category called Paging File
```
## Screenshots
![image](https://user-images.githubusercontent.com/48654399/116735697-e5d7c100-a9bc-11eb-875c-852ba5d2d3c1.png)
![image](https://user-images.githubusercontent.com/48654399/116735724-ebcda200-a9bc-11eb-871b-debf5ebc9ea8.png)
![image](https://user-images.githubusercontent.com/48654399/116735736-ef612900-a9bc-11eb-8b5a-35dee3070c39.png)
Typical gadget tab sensor setting:
![image](https://user-images.githubusercontent.com/48654399/116735799-030c8f80-a9bd-11eb-969a-8475ad9d5b1f.png)

## Files
~30s of HWiNFO sensor log, HWiNFO.inc, HWiNFOIndexList.txt:
[HWiNFO sensor log, settings, index list.zip](https://github.com/SilverAzide/Gadgets/files/6407190/HWiNFO.sensor.log.settings.index.list.zip)

**Comment by SilverAzide** [comment]
Thanks for the extensive information; it is very helpful.  I'm a little concerned about the error messages showing up in the log.  These errors seem to be the source of the problem, as they are the source of the data for the percent usage values.  (Also your paging file measure is busted as well.)

Try this first:  
[HOW TO Fix your Performance Counters database](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Fix-your-Performance-Counters-database)

Your HWiNFO config looks perfect, so my guess is your performance counters database is messed up.  Once you get these repaired, you should be good to go.  Let me know how it goes!

**Comment by SilverAzide** [comment]
P.S.:  Once you have this working, I'd go back and redo your HWiNFO settings to use Core Clock (not Core Effective Clock).  The CPU Meter does not use effective clock, so it does need just the Core Clock sensors.  Other than, everything is great (you definitely don't need the shared memory setting either, but it will uncheck itself for you, LOL).  I did notice from the info you sent that I need to fix that index list to handle super long motherboard names, so I'll do that in the next version.

**Comment by JAG836** [comment]
Repairing the performance counters fixed it. Thank you! No errors in the rainmeter log 😀

I changed my settings back to the Core Clock sensors. Sorry, I should have changed it back before I submitted this issue 👍
