### ISSUE TITLE
Chronometer drifting to GPU enhancement 

### ISSUE THREAD

**Issue by dougsmucker** [SilverAzide/Gadgets#22]
I like the chronometer but I wanted to get rid of the Day-Week-Quarter line so I modified Digital Clock.ini (attached.)

I added variable HideDWQ, setting it to 1 hides the line and shrinks the clock, setting it to 0  leaves the clock as is. I did not make the changes to Settings.ini to make this a complete enhancement. All modified lines have the original line commented out with ";DAS original line" followed by the altered line.

Fell free to incorporate or ignore this. 

Thanks again for all your work on the Gadgets,
Doug

[Digital Clock.txt](https://github.com/SilverAzide/Gadgets/files/6428543/Digital.Clock.txt)

**Comment by SilverAzide** [comment]
Thank you!  I'll see what I can do.  You are not the first to request this!  😃
But you ARE the first to actually do something about it, LOL...

**Comment by SilverAzide** [comment]
Can you give this a test for me?  (You'll need to replace your variables file, sorry!)

[Digital Clock.zip](https://github.com/SilverAzide/Gadgets/files/6429109/Digital.Clock.zip)

**Comment by dougsmucker** [comment]
Works great.  TYVM.

**Comment by dougsmucker** [comment]
A real nitpicky enhancement. I modified 2 lines of GPU Meter.ini (GPU #1) to space out the temperature and fan speed labels to be clearer. Again see ";DAS"
[GPU Meter.txt](https://github.com/SilverAzide/Gadgets/files/6429243/GPU.Meter.txt)

**Comment by SilverAzide** [comment]
That one I will leave as-is; hope you won't mind.  The original addgadgets GPU Meter used another variation, more like this:

GPU Temperature:  XX C
Fan Speed:  XX RPM
Core Voltage:  XX V

This was OK (and more consistent), but left a lot of empty space on the right side, not to mention the units of measure were bouncing around a lot as the numbers changed.  So I moved the values to the right to make it more lined up with the CPU Meter.  Not sure which is better...

**Comment by dougsmucker** [comment]
No problem at all.

**Comment by dougsmucker** [comment]
I did it so the GPU and Fan labels would more clearly (to me) apply to both the line they are on and the line immediately below them. Again - I have no problem as you have it.
![image](https://user-images.githubusercontent.com/29403495/117193342-949e4780-ad97-11eb-9452-a9337596e78f.png)

**Comment by SilverAzide** [comment]
That does look pretty good!  The original addgadget GPU Meter was a bit of a mess, and my attempt at making it better visually match up with the CPU Meter may not have been all that great.

![gpu_meter2](https://user-images.githubusercontent.com/2706567/117209228-14420b80-adc4-11eb-8897-2870b424d0ef.png)

**Comment by dougsmucker** [comment]
I think you improved it a lot. I made a VERY minor tweak. Completely your call. The more of my "enhancements" you incorporate the less work I have to do when you release a new version.
