### ISSUE TITLE
peak bandwidth 

### ISSUE THREAD

**Issue by zme-ul** [SilverAzide/Gadgets#26]
peak bandwidth means max between IN or OUT and not IN+OUT

any way I can modify the 

`[MeasureMaxBytesPerSec]`

to output `MeasureNetIn +  MeasureNetOut `

**Comment by SilverAzide** [comment]
If you would like to change the measure formula, you can use this:

`Formula=(MeasureNetIn + MeasureNetOut)`

**Comment by zme-ul** [comment]
> If you would like to change the `[MeasureMaxBytesPerSec]` measure formula, you can use this:
> 
> `Formula=Max(MeasureNetIn + MeasureNetOut, #MaxBytesPerSec#)`

I was thinking of doing exactly that but I wasn't sure about it cuz I'm not accustomed to LUA scripting

**Comment by zme-ul** [comment]
heya, since I got you with the other (dumb non-issue)

please consider making this an option in the Network Meter gadget
`Formula=Max(MeasureNetIn + MeasureNetOut, #MaxBytesPerSec#)`

**Comment by SilverAzide** [comment]
Well, you can do that, but then the stats will be wrong, won't they?  For example, your 1 Gb connection can report 2 Gb peaks, which is impossible.  The resolution of the measures is only 1 measurement per second, so it is possible that both net in and net out will be some huge value that when added together will be more than your actual throughput.

The reason I coded the skin this way is that I know my ethernet switch is a 1 Gbps switch, and adding the two values together I can easily hit 1.5+ Gbps, which is not possible.  I think the resolution of the measures/skin is too low to get a super accurate peak value.

**Comment by zme-ul** [comment]
well, this is where you are not correct
1gbps connections are mostly full duplex - what that means is theoretically 1gbps in each direction, so yes .. 2gbps is achievable **in theory**

I do have 10gbe network though, due to many limiting factors it can't actually achieve 10gigabits, but it would be nice to know the approximate throughput of the connection

**Comment by SilverAzide** [comment]
Well, I guess if that's the way it is supposed to be, then I guess the skin(s) actually need to be fixed.  So instead of being an option, then the formula you posted is the fix.

**Comment by SilverAzide** [comment]
Corrected.  Included in next release.
