### ISSUE TITLE
CPU usage over 100%.

### ISSUE THREAD

**Issue by night-herons** [SilverAzide/Gadgets#27]
I am using it with a NUC 10 Performance kit - NUC10i3FNK with Core i3-1010U.
As you can see in the attached image, the CPU usage is shown above 100%.
The same phenomenon does not occur on my other PC, the one with the i7-8700.
This may not be a problem in practical use, but please check it out

Rainmeter Version
Rainmeter 4.5.2.3541 (64-bit)
Build time: 2021-09-11 23:35:58
Windows 10 Pro 2009 64-bit (build 19043) - Japanese (1041)
Gadgets version 7.1.0
HWinfo version: 7.10-4540 64-bit

![over100](https://user-images.githubusercontent.com/28802007/133754309-001a5005-d727-435b-91fc-c4bc15e725c9.png)

**Comment by miquelfire** [comment]
It's an oddity with Intel processors. I believe that can happen during turbo boost. My 10th gen desktop doesn't something like it.
I reported something like this, but mine was more extreme for some reason: #19

**Comment by SilverAzide** [comment]
@night-herons, @miquelfire,
CPU usage over 100% is actually "correct", depending on how you define it.  Please see this wiki article:
[INFO: CPU performance exceeds 100](https://github.com/SilverAzide/Gadgets/wiki/INFO-CPU-performance-exceeds-100#info-cpu-performance-exceeds-100).

You can select the [Use Legacy Mode](https://github.com/SilverAzide/Gadgets/wiki/INFO-CPU-performance-exceeds-100#all-cpu-meter-legacy-mode) option to use the Windows 7-style usage monitoring, which does not result in values over 100%.
