### ISSUE TITLE
Request SNMP Network Monitor

### ISSUE THREAD

**Issue by lars18th** [SilverAzide/Gadgets#28]
Hi,

First, congratulations for this good job! 👍 

Second, I'm not sure if you accept requests, but I'm missing the SNMP Network Monitor widget/gadget for monitoring the Router:

![SNMP Network Monitor](http://netdogware.com/images/snmp_network_meter_gadget_face.png)

I hope you want to take a look at it!
Regards.

**Comment by SilverAzide** [comment]
Interesting!  This isn't one of the original addgadgets.com gadgets, but it is definitely interesting.  I'd like to monitor my router too, so if I can figure out how this can be done, I'll look into it.  Thanks for the info!

**Comment by lars18th** [comment]
Hi @SilverAzide ,

I'm glad you find out interesting! 😄 

Regards.

**Comment by SilverAzide** [comment]
There is a Gadget-style Ping skin in dudebaker's Gadgets Additions suite:
https://github.com/Dudebaker/Gadgets-Additions/
https://www.deviantart.com/dudebaker/art/Gadgets-Additions-4-3-1-734942129

**Comment by SilverAzide** [comment]
Deprecating this issue for now, as I have no way (or lack the know-how and hardware) to develop such a utility.
