### ISSUE TITLE
Check for Updates

### ISSUE THREAD

**Issue by kennylee33** [SilverAzide/Gadgets#31]
Hi SilverAzide, I have a question about “Check for Updates” in Gadgets. Right now I see a notification for 7.1.1 - 2021-09-18.  This update doesn’t interest me so I click “Remind me later” but the notification recurs at intervals.  Is there a way I can avoid notifications for 7.1.1 - 2021-09-18 and instead get a notification for the next release?

**Comment by SilverAzide** [comment]
Hello!  Unfortunately, I didn't think of *not* wanting to upgrade, LOL.  I guess "remind me later" really means "remind me tomorrow"... The only way to stop the nagging is either to upgrade or to extend what "later" means.  You should not lose any settings if you decide to upgrade (and I didn't make any mistakes, as I built the .rmskin to carry over all your settings).

But if you'd like to extend the nag interval from 1 day to more, then that is easy.  Open the Rainmeter Manage dialog and select the Update Checker skin and click the Edit button.  Find the meter `[MeterRemindLaterLink]`.  Adjust the `LeftMouseUpAction` line to something like this:

````ini
LeftMouseUpAction=[!SetVariable NextCheckTimestamp ([MeasureTime:TimeStamp]+86400*7)][!Hide][!Move "0" "0"]
````
This will extend the nag time to 1 week (7 days).  Just change the multiplier `...*7...` to whatever interval (in days) you want.  I don't know of a simple way to change the logic to skip the current version; it's possible, but would require some work to implement.  Perhaps I can add an enhancement in a future version.

**Comment by kennylee33** [comment]
Thanks for getting back so quickly!  I appreciate the steer on changing the interval, but for now I'm just going to upgrade to the latest.

Love them Gadgets! 😀 Thank you so much for your hard work on the project.
