### ISSUE TITLE
Enhance CPU Meter to invoke Resource Monitor or Task Manager on double-click.

### ISSUE THREAD

**Issue by SilverAzide** [SilverAzide/Gadgets#32]
Enhance the All CPU Meter gadget to invoke either the Task Manager or the Resource Monitor when the gadget is double-clicked.  This will match the behavior of the original AddGadgets.com All CPU Meter.

**Comment by excesseve** [comment]
Heuuuuh, I already get the Task Manager on double-clicking my CPU Icon in the CPU Meter.  Am I missing something ?

**Comment by SilverAzide** [comment]
Oh, sorry, I should have made my enhancement clearer!  Another user just reminded me that the original AddGadgets.com sidebar gadget had an option that allowed you to choose whether to pop up Task Manager (the default) or Resource Monitor when double-clicking the gadget.  So this enhancement request would echo the same behavior.  (I sort of worked around this by having the Top Process skins pop up Resource Monitor when double-clicked.)

**Comment by SilverAzide** [comment]
Completed.
