### ISSUE TITLE
Chronometer

### ISSUE THREAD

**Issue by Guerilla3** [SilverAzide/Gadgets#36]
Add option for a semicolon separator between minutes and seconds. As shown in picture.

![image](https://user-images.githubusercontent.com/35316123/152328785-12acac44-2124-49d5-b954-0185900b75e4.png)

**Comment by SilverAzide** [comment]
OK!  In the meantime, if you want to make the change yourself, you can do the following:

* Right-click the skin and select "Edit skin".
* Find the meter named `[MeterTime]`; change the formula for `X` to:
```ini
X=((#BgWidth# / 2) + (([CalcNumHourDigits] = 1) ? 0 : 7) + (#TimeStyle# = 0 ? 0 : 11)) - 3
```
(in other words, add "- 3" to the end to account for the width of the colon).
* Find the meter named `[MeterSeconds]`, located just below.
* Change the value of `Text` to:
```ini
Text=":%1"
```
Save the file and refresh the skin.

**Comment by Guerilla3** [comment]
Thanks for the code, looks nicer now. Already did the `Text=":%1"` before taking the picture. Cheers.

**Comment by SilverAzide** [comment]
Option added in next version.
