### ISSUE TITLE
Very slow Drives Meter load

### ISSUE THREAD

**Issue by dougsmucker** [SilverAzide/Gadgets#37]
Starting either yesterday or today my Gadgets 7.2.0 layout started taking a long time to come up. (It could have changed before then but I only reboot my PC or restart Rainmeter when required.)

I just now was prompted to update Rainmeter to 4.5.11.3607 and did so. The Rainmeter icon showed up immediately on the taskbar but the gadgets took a long time to appear.

I unloaded and loaded each gadget. All of them load instantly (less than 1 second) except the Drives Meter which took 23 seconds to load. I am not aware of any other changes to my hardware or software.

**Comment by SilverAzide** [comment]
I'm not really sure what to tell you, as the Drives Meter hasn't changed.  Perhaps try the instructions to reset your performance counters database.  Also, if you've mapped a drive letter to a non-existent (or disconnected) network drive, that could do it as well. Maybe try unchecking all the drive letters but C: to see if a particular drive is causing this.

**Comment by dougsmucker** [comment]
I had not changed my config at all. I removed all but C and it is back to normal: 1-2 second delay. Then I added back all the drives I had, and then set it back to drives C-K which was my original setting. All back to normal. Weird.

Thanks!!

**Comment by SilverAzide** [comment]
That is very weird!  The 1-2 second delay I understand (it's due to the UsageMonitor measures initializing, which this skin in particular makes extensive use of), but the super-long delay is strange.  Strange too that it went away! 😕
