### ISSUE TITLE
Network Drives

### ISSUE THREAD

**Issue by timgoat** [SilverAzide/Gadgets#38]
Is there a workaround for monitoring network drives?

**Comment by SilverAzide** [comment]
Network drives aren't "drives", so there's no way to monitor them.  By that I mean Windows does not monitor read/write stats on these, nor does it even consider the drives as logical devices, so there's no way to report any stats other than disk space.

If you want to force them to show up in the Drives Meter anyway, you can adjust the code.  Basically, you can do a search and replace.  Search for the following:
```ini
(MeasureDiskTypeN = 3) || (MeasureDiskTypeN = 4)
```
where the "N" is the drive letter, A thru Z (so there's 26 instances to fix).  Replace the expressions with:
```ini
(MeasureDiskTypeN >= 3) && (MeasureDiskTypeN <= 5)
```
After this, you will ~~probably~~ definitely need to uncheck the "Show Percent Disk Time Histogram" option, as it won't work for network drives.

BTW, if the network drive loses connectivity with the server, it will cause Rainmeter to begin pausing (freezing) at 1 second intervals as it tries to query the drive, so be aware of this (it is not a skin issue).

---
**EDIT:**
For anyone else finding this post who is familiar with Notepad++ and doing regular expression find-and-replaces, you can do the replacement in one shot using the following:

Find what:
```ini
\(MeasureDiskType(.) = 3\) \|\| \(MeasureDiskType(.) = 4\)
```
Replace with:
```ini
\(MeasureDiskType\1 >= 3\) && \(MeasureDiskType\2 <= 5\)
```
