### ISSUE TITLE
2- or multicolumn drives meter

### ISSUE THREAD

**Issue by psisis** [SilverAzide/Gadgets#39]
With a lot of drives the drive meter skin gets very long. I want to request a setting to display at least 2 columns of drives and a wider graph to fit accordingly.

**Comment by SilverAzide** [comment]
Yes, I understand, it is that way with CPUs with lots of cores too.  But the Gadgets are all uniform widths, so I don't see me making an extra wide one; it is much too difficult and would require a completely separate skin (not just a setting).  Your best alternative is to create two Drives Meters, then configure each one to monitor a different set of drives.  Then you can position the skins side by side.  Not a great alternative, but one that you can do easily.

If you want to try this approach, all you need to do is create a new skin folder at the same level as the Gadgets folder, then copy the @Resources, Settings, and Drives Meter folders from the main Gadgets folder into it.  Something like this:

![image](https://user-images.githubusercontent.com/2706567/158024835-a406f795-9fe2-4e73-b5f8-4b72115fdd37.png)

After you do a refresh of Rainmeter, you'll have a completely independent Drives Meter skin.
