### ISSUE TITLE
GPU meter problem

### ISSUE THREAD

**Issue by harry717yam** [SilverAzide/Gadgets#40]
hi Silver Azide

my computer GPU is ASUS TUF RTX3080 LHR,
rainmeter is 4.5.13 ,HWiNFO64 is 7.20
and your Gadgets is 7.20

but the GPU meter is not configured
is that setting or somthing wrong?

**Comment by SilverAzide** [comment]
Did you follow the instructions to configure HWiNFO and the GPU Meter?  If not:
- [HOW TO Configure HWiNFO](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Configure-HWiNFO#how-to-configure-hwinfo)
- [HOW TO Configure the GPU Meter](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Configure-the-GPU-Meter#how-to-configure-the-gpu-meter)

**Comment by SilverAzide** [comment]
Just following up... Did you get this working?

**Comment by SilverAzide** [comment]
No response.
