### ISSUE TITLE
Core Voltage not shown in GPU meter

### ISSUE THREAD

**Issue by Siggi0904** [SilverAzide/Gadgets#41]
Hi,
I configured the CPU- and GPU-Meter and nearly all values are shown.
Using the latest version 7.2.0 of the Gadgets for Rainmeter. Rainmeter is latest version.
But the core voltage of the GPU isn't shown.
(RPM at 0 is right, HWInfo update here no values, have to check it in parallel)

Why the core voltage isn't shown?
Thanks for helping.

Actual status:
![grafik](https://user-images.githubusercontent.com/4992106/160276824-defabab2-6540-490f-b9d9-2c5415623007.png)

Values in HWInfo:
![grafik](https://user-images.githubusercontent.com/4992106/160276923-2fbaf355-8633-4cc2-8344-0722f0444e3a.png)

Exported values to gadget:
![grafik](https://user-images.githubusercontent.com/4992106/160276954-34245166-7582-4e01-9354-1b6ab4e5a848.png)

**Comment by SilverAzide** [comment]
Hello!  The only reason I can think of is that the sensor index for the voltage isn't set.  Open the HWiNFO.inc file and look for the variable HWiNFO_GPU0_CoreVoltage and make sure it is set to 26 (per your index list above):
```ini
; GPU core voltage (volts)
HWiNFO_GPU0_CoreVoltage=26
```
Let me know if this helps.

**Comment by Siggi0904** [comment]
Hi,

it is set. See in settings file.
`; -------------------------------------------- GPU #0 ----------------------------------------------
;
;   (For AMD GPUs, see the "SPECIAL NOTE Regarding AMD GPUs" above.)
;   (HWiNFO may not show GPU #0 in cases where you have a dedicated graphics card.)
;
; GPU temperature (degrees)
HWiNFO_GPU0_Temp=25
; GPU core voltage (volts)
HWiNFO_GPU0_CoreVoltage=26
; GPU core clock frequency (MHz)
HWiNFO_GPU0_Clock=29
; GPU memory clock frequency (MHz)
HWiNFO_GPU0_MemoryClock=30
; GPU core load (percent)
HWiNFO_GPU0_CoreLoad=31
; GPU memory usage (percent)
;   NOTE: for *most* nVidia GPUs, this sensor reports the percentage of RAM in use
;   NOTE: for *rare* nVidia GPUs that do NOT have a sensor for memory usage (percent), you MUST set this value to blank
;   NOTE: for all AMD and Intel GPUs, you MUST set this value to blank since this sensor does not exist
HWiNFO_GPU0_MemoryUsage=32
; GPU memory allocated (MB)
;   NOTE: for nVidia GPUs, set the following value to the index of the "GPU Memory Allocated" sensor (i.e., amount of VRAM allocated, in megabytes)
;   NOTE: for *some* AMD GPUs, set the following value to the index of the "GPU Memory Usage" sensor (i.e., amount of VRAM allocated, in megabytes)
;   NOTE: for *most* AMD GPUs, set the following value to blank since there is no sensor available to report allocated VRAM
;   NOTE: for Intel GPUs, set the following value to blank since there is no sensor available to report allocated VRAM
HWiNFO_GPU0_MemoryAlloc=35
; GPU fan usage (percent, not RPM!)
;   IMPORTANT: if your GPU sensor does not report fan usage, set the following value to blank
HWiNFO_GPU0_FanUsage=33
; GPU fan speed (RPM)
;   NOTE: the GPU fan speed sensor can be either on the graphics card or the motherboard, depending on your hardware
HWiNFO_GPU0_GPUFanSpeed=27

; GPU #0 RAM: for AMD GPUs, enter the total amount of dedicated RAM in megabytes (1 GB = 1024 MB)
;             for *most* nVidia GPUs that report memory usage (percent), you MUST set this value to 0 (zero)
;             for *rare* nVidia GPUs that do NOT report memory usage (percent), enter the total amount of dedicated RAM in megabytes (1 GB = 1024 MB)
;             for Intel GPUs, you MUST set this value to 0 (zero), as these GPUs have no dedicated RAM.
GPU0_MemoryTotal=12288`

**Comment by SilverAzide** [comment]
OK, great!  I was expecting you did it properly, but I had to ask.  🙂

I am suspecting that what we have is a problem with internationalization; specifically, the conversion of decimal values.  I'm not exactly sure where to point the blame, it could be Rainmeter, or just the way registry values are handled in Rainmeter.

Where I'm going with this is that HWiNFO is writing the sensor values to the registry as strings (not numbers), and it is using the numeric formatting defined by your locale (e.g., "1.234,567").  Rainmeter is reading these values as a string and will need to convert these to numeric/decimal values.  I'm wondering if Rainmeter is encountering the German-style comma separator and truncating the data.  So anything after the decimal is being lost, thus your voltages are all zeros.

So you check this by looking at the Rainmeter About window. Select the Skins tab and the GPU Meter.  Look at the string and number values of the sensor measures:
![image](https://user-images.githubusercontent.com/2706567/160289745-13ceb1b5-618e-4763-b7e9-699e77c90337.png)

What you _should_ see is that the string values and numeric values match.  However, if you see that everything after the comma (if present) is being lost, then Rainmeter is not converting properly.  Check the voltage measure specifically as well.

If everything looks good, then the problem could be with the way registry measures work, in that often they don't convert strings to numbers properly when you use the value.  If so, I can add a work-around to force the conversion to a number.

If everything looks bad (i.e., decimals are being truncated), this is a bigger issue and could be a Rainmeter problem.  There is a simple workaround (but it is annoying for you).  HWiNFO allows you to define the decimal separator and the thousands separator (this is found on the Sensor Settings window in HWiNFO).  Change your decimal separator to "." and the thousands to nothing ("") and see if Rainmeter/the Gadgets start working properly.

**Comment by Siggi0904** [comment]
Yes, you are right.
That's my values at rainmeter about:
![grafik](https://user-images.githubusercontent.com/4992106/160291642-11686e80-847a-4c53-bea9-91f3b7fde542.png)

After your described changes at decimal seperator, the value is shown in the gadget.
See:
![grafik](https://user-images.githubusercontent.com/4992106/160291773-3430ae20-afa5-4a82-b29a-d47780e83195.png)

**Comment by SilverAzide** [comment]
Glad it is working! But I guess the bigger issue is that, for some reason, Rainmeter is not converting strings to numbers properly.  I will post this on the Rainmeter forum and see if anyone else is having this issue.  It seems like a bug to me.

**Comment by SilverAzide** [comment]
P.S.:  I see in your screenshot that the voltage and RAM values are not actually displaying properly.  They should appear like "1,089 GB" and "0,656 V", etc.  So it is like Rainmeter is showing everything in English-style formatting.

Is your Windows set to US or UK English by any chance?  I know a lot of people set Windows to US-English to make things simpler, especially if they do a lot of international work.  If your base Windows installation is US-English and Rainmeter/HWiNFO is German, then perhaps this is just a localization conflict.

**Comment by Siggi0904** [comment]
No, system and HWinfo is configured to german language with german decimal seperators.
As far as I saw,HWInfo will only switch language and doesn't change anything else.
And yes, looks like localizion conflict. But why I'm the first with these problem. :-)

Thanks for forwarding and checking it with HWinfo devs.
