### ISSUE TITLE
Allow hybrid units to be shown in weather gadget

### ISSUE THREAD

**Issue by Razzle69** [SilverAzide/Gadgets#43]
Please enhance the weather gadget to allow showing hybrid units.  Both celsius and fahrenheit.

**Comment by SilverAzide** [comment]
Unfortunately, I don't see how to do this in a practical way.  The main problem is there's no room on the Weather Meter skin to fit both values.  The only way would be if the main temperature value was made much smaller so both values could be crammed in somehow.  The other temps are way too cramped already, so they would need to stay as is, in whatever units the data is in.

Don't get me wrong, it is a pretty simple tweak actually.  All you need is one new meter (maybe two depending on how the temps are shown) and a little Lua function for the temperature conversion.  I don't really see me adding this as a built-in feature, but if you want to make the change yourself, I can give you some instructions and some code to paste into the skin.

**Comment by SilverAzide** [comment]
Contact me if you want to add this yourself.
