### ISSUE TITLE
Top CPU Meter wrong measure

### ISSUE THREAD

**Issue by chizhov-alex** [SilverAzide/Gadgets#45]
Top CPU Meter show lower cpu usage then the Task Manager. It feels like the Task Manager shows the correct values.
Windows 11 22H2
Gadgets 7.3.0
Rainmeter 4.5.13.3632
![image](https://user-images.githubusercontent.com/60903811/172735686-d597d737-71d4-41b7-8cb2-83013e4f597d.png)

**Comment by SilverAzide** [comment]
Hello!
The values shown in the Top CPU Meter skin are coming from the Windows Performance Counters database, as given by Rainmeter.  I have no idea where the values in Task Manager are coming from, I would assume the same place.  I have no idea if processor overclocking is accounted for or not.  And for what it is worth, I see similar results on my machine as you do, so it is not just you.

One thing to keep in mind is that the sampling that is done by both apps is done at different times, so unless you have a pretty stable process running you might see different numbers bouncing around from one second to the next.

In any case, there nothing I can do about this; if there is a problem, it is a problem with Rainmeter.  The numbers are coming straight from there.  Sorry!
