### ISSUE TITLE
CPU Meter "Temp" Color

### ISSUE THREAD

**Issue by thowtue** [SilverAzide/Gadgets#48]
Hello,
Got issue or maybe feature missing, but when i change the Core 1 color it changes the Temp too (as i'm not using per core temps bc i have AMD) so the Temp color is linked to the Core 1 color and i'd like to make them different colors
Can you do something about this ?

**Comment by SilverAzide** [comment]
Hello!
Actually, the "Temp" color changes dynamically based on the CPU temperature.

![image](https://user-images.githubusercontent.com/2706567/182960105-7991e6ba-2b21-4798-9cc0-57211c71d877.png)![image](https://user-images.githubusercontent.com/2706567/182960233-628c0ca1-281c-4995-9525-11b8cf619d7b.png)

It will go from blue, green (color #1), yellow (color #2), orange (color #3), to red (color #4) based on the temp.  If you want to change this, you will need to edit the skin.  Open the CpuMain.inc file with your preferred editor and locate the measure `[CalcCoreTempPercentTjMax]`.  Change the colors referenced in this measure to anything you want.

**Comment by thowtue** [comment]
I tried to change the value, but seems to have no effect at all, seems locked on "Core 1 Temp" color (PaletteColor1) even if i put PaletteColor2 on core temps between 25 to 90. Even the bar does not seem to change color too.

The code :

`[CalcCoreTempPercentTjMax]
Measure=Calc
Formula=((#UseTjMaxOverride# = 0) ? (Clamp(MeasureCoreTempMaxTemp / ((MeasureCoreTempTjMax = 0) ? #TjMaxOverride# : MeasureCoreTempTjMax), 0, 1) * 100) : Clamp(MeasureCoreTempMaxTemp / #TjMaxOverride#, 0, 1) * 100)
MinValue=0
MaxValue=100
IfCondition=(CalcCoreTempPercentTjMax <= 25)
IfTrueAction=[!SetOption MeterTemperatureBarPrompt FontColor "#ColorInfoText1#"][!SetOption MeterMaxTemperature FontColor "#ColorInfoText1#"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
IfCondition2=((CalcCoreTempPercentTjMax > 25) && (CalcCoreTempPercentTjMax <= 60))
IfTrueAction2=[!SetOption MeterTemperatureBarPrompt FontColor "#PaletteColor2#"][!SetOption MeterMaxTemperature FontColor "#PaletteColor2#"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
IfCondition3=((CalcCoreTempPercentTjMax > 60) && (CalcCoreTempPercentTjMax <= 80))
IfTrueAction3=[!SetOption MeterTemperatureBarPrompt FontColor "#PaletteColor2#"][!SetOption MeterMaxTemperature FontColor "#PaletteColor2#"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
IfCondition4=((CalcCoreTempPercentTjMax > 80) && (CalcCoreTempPercentTjMax <= 90))
IfTrueAction4=[!SetOption MeterTemperatureBarPrompt FontColor "#PaletteColor2#"][!SetOption MeterMaxTemperature FontColor "#PaletteColor2#"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
IfCondition5=(CalcCoreTempPercentTjMax > 90)
IfTrueAction5=[!SetOption MeterTemperatureBarPrompt FontColor "#PaletteColor4#"][!SetOption MeterMaxTemperature FontColor "#PaletteColor4#"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
DynamicVariables=1
Disabled=1`

The result : 
![image](https://user-images.githubusercontent.com/34699555/183084937-7f8d3eab-8ead-4204-90f5-46b5583f0808.png)

**Comment by thowtue** [comment]
My bad, didn't wanted to close sorry

**Comment by SilverAzide** [comment]
My apologies, you didn't mention which temperature monitoring utility you were using, so I gave you the info assuming CoreTemp.  If you are using HWiNFO, the measure you need to change is named `CalcHWiNFOPercentTjMax`.  If you are using SpeedFan, the measure to change is `CalcSpeedFanPercentTjMax`.

(In case it is an issue, I see the code you posted got somehow mangled, so make sure you are using a text editor that is using Windows CR/LF line endings, not Unix-style line endings.)

Here is the code I used.  I set the color to a specific value (`0,110,255`), but you can use a predefined color variable or any other value you prefer.

```ini
[CalcHWiNFOPercentTjMax]
Measure=Calc
Formula=((#UseTjMaxOverride# = 0) ? (Clamp(MeasureHWiNFOMaxTemp / ((MeasureHWiNFODistToTjMax = 0) ? #TjMaxOverride# : MeasureHWiNFOCpu1 + MeasureHWiNFODistToTjMax), 0, 1) * 100) : Clamp(MeasureHWiNFOMaxTemp / #TjMaxOverride#, 0, 1) * 100)
MinValue=0
MaxValue=100
IfCondition=(CalcHWiNFOPercentTjMax <= 25)
IfTrueAction=[!SetOption MeterTemperatureBarPrompt FontColor "0,110,255"][!SetOption MeterMaxTemperature FontColor "0,110,255"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
IfCondition2=((CalcHWiNFOPercentTjMax > 25) && (CalcHWiNFOPercentTjMax <= 60))
IfTrueAction2=[!SetOption MeterTemperatureBarPrompt FontColor "0,110,255"][!SetOption MeterMaxTemperature FontColor "0,110,255"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
IfCondition3=((CalcHWiNFOPercentTjMax > 60) && (CalcHWiNFOPercentTjMax <= 80))
IfTrueAction3=[!SetOption MeterTemperatureBarPrompt FontColor "0,110,255"][!SetOption MeterMaxTemperature FontColor "0,110,255"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
IfCondition4=((CalcHWiNFOPercentTjMax > 80) && (CalcHWiNFOPercentTjMax <= 90))
IfTrueAction4=[!SetOption MeterTemperatureBarPrompt FontColor "0,110,255"][!SetOption MeterMaxTemperature FontColor "0,110,255"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
IfCondition5=(CalcHWiNFOPercentTjMax > 90)
IfTrueAction5=[!SetOption MeterTemperatureBarPrompt FontColor "0,110,255"][!SetOption MeterMaxTemperature FontColor "0,110,255"][!UpdateMeter MeterTemperatureBarPrompt][!UpdateMeter MeterMaxTemperature]
DynamicVariables=1
Disabled=1
```

You didn't mention you wanted to change the bar color.  This bar is an image, not one that is a configurable color.  To change the bar, you need to edit the meter `[MeterBarTemperature]`.  Comment out the line that specifies the image, then add the line that specifies the `BarColor` option; again you can use whatever color you want.

```ini
[MeterBarTemperature]
Meter=Bar
MeterStyle=StyleBar | StyleAllBar
MeasureName=CalcCoreTempPercentTjMax
;BarImage=#@#BarGradient.png
BarColor="0,110,255"
Hidden=#HideTempBar#
```

Here is the result:
![image](https://user-images.githubusercontent.com/2706567/183217877-4bd446f6-9e74-4a3d-a696-05582b701dec.png)

**Comment by thowtue** [comment]
Allright i've found it, thank you ! 
I tried also to change directly by the color first like you've done but found aout that havent changed anything so i thought i was wrong so i replaced by `#PaletteColor2#` and nothing too, but i've go the changes now and it works sorry for not precise that i was using HWinfo, i should have scrolled down a bit more and find it myself, and find the solution haha, but thank you :)

Also didn't know why the code was rendered like that, i'm using np++ and pasted it directly from it so dunno why :/

Also, big thanks for making these monitoring tools, i'm using them for a while now, when it was on deviant art :)

**Comment by SilverAzide** [comment]
Glad you are enjoying the Gadgets!  👍 

The Gadgets are still available on DA **[here](https://www.deviantart.com/silverazide2/art/Gadgets-7-3-0-860144257)**, but Github or the Rainmeter forums are the best places to get them and to ask questions, as I don't check DA very often.

**Comment by thowtue** [comment]
Oh okay, i saved a page on DA when i downloaded years ago, and it was 404 when i tried to reach it, so i searched on google an found you've updated it on Github
