### ISSUE TITLE
Gadgets causing Rainmeter to hang?

### ISSUE THREAD

**Issue by phreich9** [SilverAzide/Gadgets#52]
Hi,
I am experiencing all of the gadgets being frozen, and the Rainmeter icon is also frozen (when I rightclick on it, nothing happens).

I have followed your documented procedure for rebuilding the perfmon databases, twice, rebooting afterwards each time, and I get the same result.  The gadgets paint very slowly during the bootup, and then are frozen, as is Rainmeter itself.

I tried uninstalling rainmeter and downgrading to the previous version but that didn't help.  I have updated to the latest version of your gadgets and that didn't help.

One thing that seems a bit odd that I noticed, is that when I click on the "show desktop" button, the clock shows the correct time, but the second hand is frozen, and the clock does not advance while I am on the desktop.

I also did an SFC /scannow, and had no errors, and did a DISM /Online /Cleanup-Image /ScanHealth to verify that my windows installation was healty -- no issues there.

This started happening within the last couple of weeks.  I can't pinpoint it to any individual event, but it could be related to a recent windows 10 update?

Any help would be appreciated.

This is on an HP z460 workstation with an 8 core Xeon E5-4655 v4, 64GB memory running windows 10 pro 64bit 21H2 with all updates, and an NVIDIA GeForce GTX 1060 3GB video card using the more "stable" "enterprise" "Studio Driver" (installed after the "Geoforce game ready driver" started to hang my system when the screen was turned off).

Philip

**Comment by phreich9** [comment]
Thanks for suggesting the way to find the culprit.
The one causing the issue is the drivemeter.  All the others run and refresh properly, but when I start the drivemeter, all the gadgets and rainmeter lock up.

**Comment by phreich9** [comment]
I have one other issue that's happening on another machine (a windows 11 pro machine).  When I go into the gadget's settings, and try to edit the hwinfo64 sensor settings for the gadgets, clicking on the "List HWinfo indexes" or the "Edit HWinfo settings" links in the settings does nothing.  It doesn't open the page to assign the values.  On that machine I am running the latest version of hwinfo64, and have turned on the "Enable reporting to gadget" option in the sensors settings.

Any suggestions to get this working?  It's an older machine running an Intel Core 2 quad Q6700 with 8GB of ram and an AMD Radeon R5 240 1GB video card, running Win 11 pro x64.  The gadgets are running fine there, I just can't configure the GPU and CPU settings to show the correct sensors from HWINFO64

Do you want me to open another issue, or deal with it here?

**Comment by SilverAzide** [comment]
> I have one other issue that's happening on another machine (a windows 11 pro machine). When I go into the gadget's settings, and try to edit the hwinfo64 sensor settings for the gadgets, clicking on the "List HWinfo indexes" or the "Edit HWinfo settings" links in the settings does nothing. It doesn't open the page to assign the values. On that machine I am running the latest version of hwinfo64, and have turned on the "Enable reporting to gadget" option in the sensors settings.
> 
> Any suggestions to get this working? It's an older machine running an Intel Core 2 quad Q6700 with 8GB of ram and an AMD Radeon R5 240 1GB video card, running Win 11 pro x64. The gadgets are running fine there, I just can't configure the GPU and CPU settings to show the correct sensors from HWINFO64
> 
> Do you want me to open another issue, or deal with it here?

Let's move this to a new issue, but first, one simple thing you can check.  Open Rainmeter > Manage > Settings and double-check that the Editor that is listed there actually exists.  Both the items you mention above are simply trying to open your text editor so you can edit/view the file.  It sounds like that command is failing.

**Comment by SilverAzide** [comment]
> Thanks for suggesting the way to find the culprit. The one causing the issue is the drivemeter. All the others run and refresh properly, but when I start the drivemeter, all the gadgets and rainmeter lock up. I haven't added a drive in months, so I don't know what change caused the issue.
> 
> I am running an NVMe SSD as my system drive, and a couple of raid 5 arrays of SAS drives connected to an HP p812 raid controller in a PCI-E slot. The gadget was working fine with these less than a month ago.

OK, this is strange.  One thing that has caused issues for me in the past is if I map a network drive to a drive letter, then for some reason that network drive no longer exists (i.e., the drive is mapped to a dead share or the server is offline).  Rainmeter will keep trying that drive once a second to check it's status.  There will be a long delay as Windows tries and retries accessing that drive, and finally gives up.  That duration is more than a second, so effectively during that time Rainmeter is hung.  The Gadget checks ALL drives (even network drives) except ones you have unchecked so they are ignored.

To fix this, verify that you don't have any network drives marked "Disconnected" in Windows, or make sure you have unchecked it to ignore it.  One thing you can do to debug is open the file `C:\Users\<username>\Documents\Rainmeter\Skins\Gadgets\@Resources\DrivesVariables.inc` and set all the "HideDisk*N*" variables to "1" except for disk C.  Then load the skin and see if it crashes.  If all is OK, open the Settings and check one drive at a time until there is a problem.  That will be the problematic disk.

**Comment by phreich9** [comment]
I tried what you suggested, changing all the HideDiskx variables but C to 1, and it still hung when I attempted to activate the Drives gadget.  I tried disabling them all, including C, but it still hung.

One other strangeness I noticed is that sometimes (not always), the CPU and TopCPU meters seem a bit hung for a while when they start up, and then eventually refresh and start working.

I turned on logging in Rainmeter, and then restarted rainmeter, and ran all my normal gadgets except the drives gadget, then I started the drives gadget, and it hung.  I have attached the log file, but it doesn't seem to show anything abnormal, except that the last thing logged was the refresh of the drives gadget.
[Rainmeter.log](https://github.com/SilverAzide/Gadgets/files/9680770/Rainmeter.log)

One thing that possibly might be have occurred around the time the gadgets stopped working is that I set my documents folder to backup to a onedrive account I have for some volunteer work I do.  I didn't realize it was actually going to change the documents folder location to the onedrive name, which is a bit lengthy.  Could the file name length be a cause of the issue?  You can see the full path in the SKINPATH variable shown in the log.

**Comment by SilverAzide** [comment]
The brief delay you see on some gadgets, particularly the CPU and GPU Meters, is normal.  They are not hung actually, it's Rainmeter's UsageMonitor plugin preparing to fetch a ton of data from the Windows Performance Counters database.  There is a background thread running that is initializing the data, and so for a second or so, no data is coming in.

So you disabled ALL the drives and it still hung up?  😮  That's super strange.  So when you did that, there are only 4 measures left running.  Try the following.  Open the `Drives Meter.ini` file.  Do a search for "[MeasureDiskIdleTimeAll]".  Comment out the entire measure AND the next three, i.e., down to and including "[MeasureDiskWriteAll]".  Save and then load the skin and see what happens.  There will be errors due to the missing measures, but at least we'll see if the problem continues.

Finally, you mentioned OneDrive.  This is just me personally, but I despise OneDrive for the very reason you noted, that it takes over your Documents folder.  As a result, I either turn OneDrive off completely, or if I can't (like on my work machines), I move the Rainmeter skins folder to someplace else.  If you want to move the default skins folder, go to Rainmeter > Manage > Settings and click the "Edit Settings" button.  At the told of the file you'll see a `[Rainmeter]` section with a setting named `SkinPath`.  Just change this to some other location and restart Rainmeter (move or copy your skin folder before restarting).

**Comment by SilverAzide** [comment]
Please let me know if you are still having this issue.

**Comment by SilverAzide** [comment]
No response.  Closing issue.

**Comment by CBongo** [comment]
FWIW, I experienced this problem as well on Win11 (freezing for a few minutes, notably when connecting and disconnecting from VPN).  Unchecking network drives in Drives Meter resolved it.

**Comment by SilverAzide** [comment]
Not unchecking network drives in Drives Meter will **definitely and absolutely** hang Rainmeter.  It's not a permanent hang, but it will hang for about 1 minute until the Windows APIs Rainmeter uses time out.  It's not the Gadgets, it's really the `FreeDiskSpace` measures in Rainmeter.  If a network drive becomes disconnected, they will immediately hang up until they time out.  I strongly recommend unchecking network drives in Drives Meter to prevent this.
