### ISSUE TITLE
RAM not showing in All CPU Meter.

### ISSUE THREAD

**Issue by britrb** [SilverAzide/Gadgets#53]
RAM Usage not showing in the All CPU Meter. Is this a DDR5 thing?

**Comment by SilverAzide** [comment]
Hello!  I don't think it is a DDR6 issue; I'm using a machine with DDR5 RAM and the CPU Meter is working fine.  Can you clarify what you mean by RAM usage is not showing?  Is everything all zeros?  Are you using a machine with multiple processors or running in NUMA mode?  What version of Windows are you running?  Have you tried [rebuilding your performance counters](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Fix-your-Performance-Counters-database)?

**Comment by britrb** [comment]
Hi there, Its a single CPU, Windows 10 x64. Whats NUMA mode? Rebuilding performance counters didnt work.
![Screenshot 2022-10-13 133106](https://user-images.githubusercontent.com/110623865/195596780-7c137835-cf41-4803-af46-5fdcd1cd4f3c.jpg)

Thanks for the quick reply, I've used your Gadgets for Years. They are so useful :)

**Comment by SilverAzide** [comment]
Odd.  Not sure what is going on here.  Your system appears to be missing some Performance Counters (or they are not working as expected).

Can you try the following?
+ Confirm that you are using the `Node #0` skin.  The easiest way to do this is to open the Rainmeter About window and on the skins tab, you should see the list of all active skins, something like this:</br>
![image](https://user-images.githubusercontent.com/2706567/195624574-76a3cee5-b056-418e-9a24-3f704bf7f89e.png)</br>If you are using a different skin, change to the `Node #0` one and check if the RAM values are appearing.

+ Check that the Performance Counters exist.  Open a PowerShell window and enter the following command:
```powershell
(Get-Counter -ListSet  "NUMA Node Memory").PathsWithInstances
```
Let me know what you get (if anything).  If you get a list of counters, then try the command:
```powershell
Get-Counter "\NUMA Node Memory(0)\Total MBytes"
```

+ Finally, try the following work-around (this will definitely work, but I'd like to know the above too).  Open the `Gadgets\@Resources\CpuVariables.inc` file.  Change the line `UseLegacyRAMOverride=0` to `UseLegacyRAMOverride=1`, then save and refresh the skin.  This will use the old-style method of getting RAM stats.

**Comment by britrb** [comment]
AH!! All working now, thank you very much :) The thing that worked was the "UseLegacyRAMOverride=1" thingy..
![Screenshot 2022-10-13 163811](https://user-images.githubusercontent.com/110623865/195643390-da510e60-4d73-483f-a28b-6a1a193a6c71.jpg)

Here's what I got in Powershell though.
![Screenshot 2022-10-13 163628](https://user-images.githubusercontent.com/110623865/195643476-864c1c89-3dce-4e68-b0c4-996b7d18526a.jpg)

Here's a wee shot of my layout 100% working :) 
![smol](https://user-images.githubusercontent.com/110623865/195644240-87f09fec-a645-4b8b-8f97-536d4e08e92b.jpg)

**Comment by SilverAzide** [comment]
Glad you got it working!  I'm totally shocked you do not have those performance counters!  They were supposed to have been added as part of Windows 8.  I guess I will need to somehow try to detect this case and set that work-around switch automatically.  Hm...

Nice "wee shot" of your desktop, LOL!  Very nice!
