### ISSUE TITLE
Add Option to Hide Used/Free/Total RAM on CPU and GPU Meters

### ISSUE THREAD

**Issue by SilverAzide** [SilverAzide/Gadgets#56]
See this post for info:  https://forum.rainmeter.net/viewtopic.php?t=20699&start=960

**Comment by miquelfire** [comment]
I think the widget you based this on had this option, but I always wanted to get rid of the bar for the RAM.

**Comment by SilverAzide** [comment]
Do you mean get rid of the bar only, or get rid of both the bar **and** the numbers at the top?  I can't get the old sidebar gadget to work on my system anymore (keeps crashing for some reason), so I can't see (or remember!) how it used to work.  😞

**Comment by miquelfire** [comment]
I want to get rid of the bar only. For me, I just don't like the redundant information, so either or being able to toggle off would be nice.

Since I switched to Windows 10, I haven't used the old sidebar gadget, so I don't remember which toggle (if not both) was present.

I guess maybe a toggle for each?

**Comment by SilverAzide** [comment]
Yes, agreed, it is redundant... I'm trying to come up with a solution that isn't a mess to implement, especially since the Settings skin is getting to be too tall.  The "show page file" option turns both values (stats *and* bar) on or off, but I doubt anyone would want a RAM option to work that way.

I'm trying to think of a way to avoid having 4 settings (show RAM stats, show RAM bar, show Page stats, show Page bar).

**Comment by SilverAzide** [comment]
Enhancement included in next release.
