### ISSUE TITLE
Weather Meter broken again?

### ISSUE THREAD

**Issue by spiff72** [SilverAzide/Gadgets#6]
Weather meter is stuck on connecting again.  It was working up until this morning with no issue.  I just grabbed the latest from the releases and it didn't help (not sure if i was outdated or not).

**Comment by SilverAzide** [comment]
Yes, I know.  :-(  Around noon or so yesterday, weather.com made a change to the way they format their data and it -- AGAIN -- broke all weather.com based skins, not just the Weather Meter skin.  They also broke the way the handle non-Latin alphabets too.  All the devs are working on a fix.

I have a work-around that fixes the problem, but it only works if you use English (US, CA, GB, etc.).  I can post the fixed files if anyone is interested, otherwise hang on and I'll post a proper update as soon as one becomes available.  Thank you for your patience!

**Comment by spiff72** [comment]
English works for me ;-)

I would be happy to try the fix if you will share the file(s) needed.

Thanks!

**Comment by spiff72** [comment]
I get a 404 not found error on that link.

**Comment by SilverAzide** [comment]
Sorry about that.  Try again...  or just go to the main page here:  https://github.com/SilverAzide/Weather-Meter-Patch

**Comment by spiff72** [comment]
OK - the first link still doesn't work, but the main page link did.

However, in following the instructions, copying those 4 files didn't seem to work.  It still says "connecting", but now there is also a small yellow triangle with an exclamation point in the upper left corner of the widget.

I tried shutting down rainmeter and relaunching it, as well as unloading and reloading the skin, but these didn't help either.

The instructions also mentioned that the location of the resources folder is in the users documents folder, but mine was one level up, in the "root" of the users folder.  Again - not sure that makes a difference or not.

Thanks!

**Comment by SilverAzide** [comment]
Dang it, I don't know why it's giving a 404.  I have tested it multiple times.  Grr.
Anyway, it is critical the files go in the Rainmeter\Skins\Gadgets\\@Resources folder.  Any other place will not work.

**Comment by spiff72** [comment]
OK - but I did place the files into that folder (overwriting the existing files).  It didn't fix the issue with the "Connecting" display.

Here is a screen shot of the skin - which only changed slightly to add the yellow triangle.  I can provide further details if you tell me what to look for and provide.
![Connecting error](https://user-images.githubusercontent.com/11482743/88946163-e93af200-d25c-11ea-80ec-3369bbb586d3.png)

**Comment by SilverAzide** [comment]
Sorry about that, I was in a rush and did not notice that the template files from the Rainmeter folks had changed names.  Try downloading a fresh copy of the zip file and install the files again.  It should work this time...  I hope.  :-D

**Comment by spiff72** [comment]
Yaay!  That change got it working again.  Thanks!

**Comment by spiff72** [comment]
And I love your avatar pic.  The "spiff" in my username is inspired by Spaceman Spiff.

**Comment by SilverAzide** [comment]
LOL!  My goal in life is to acquire an Atomic Napalm Neutralizer.

**Comment by spiff72** [comment]
Nice.  I would like a Transmographier, personally.

**Comment by mufiskilo** [comment]
Thanks! SilverAzide

**Comment by Slade1972** [comment]
Thanks for fixing this so quickly. I was pretty bummed it had stopped working again.

**Comment by SilverAzide** [comment]
You're welcome!  One of the Rainmeter devs is creating a new set of weather.com files, which should be out very soon (today or tomorrow). Once they are out, I'll release a new version of the Gadgets as quickly as possible.

If anyone has not upgraded to the latest Rainmeter 4.4 beta, I would urge you to do so.  It contains a critical bug fix that for the first time will allow all your Gadgets settings to be properly saved, so when you upgrade the Gadgets, all your settings will be preserved.  (Previous versions of Rainmeter only preserved _most_ settings, not _all_.)  The next release of the Gadgets will still work (and install) with 4.3.1, but 4.4.x is highly recommended.

**Comment by SilverAzide** [comment]
Fixed in v5.5.0.

**Comment by sanusigogo** [comment]
when is the burning day
