### ISSUE TITLE
discrepancy between Newtwork Meter and iperf3

### ISSUE THREAD

**Issue by zme-ul** [SilverAzide/Gadgets#61]
I did some testing between the NAS and my desktop, seems Network Meter doesn't "measure" the bandwidth correctly - note the peak vs iperf3 bandwidth 

![image](https://user-images.githubusercontent.com/25272649/201207144-767c2b32-7703-4855-9059-fb6b86a1ff25.png)

I tried with and w/o the Net Monitor Service installed

note: Gadgets v7.5.0

---

after some more testing: if I shift down the link to 5gbe, the iperf3 result and the peak bandwidth about match

![image](https://user-images.githubusercontent.com/25272649/201209268-39b6ea8e-2296-4a2c-a368-5e4c59e8f188.png)

it seems there's a issue with 10gbe links

**Comment by SilverAzide** [comment]
Good lord, that is a beast of a machine...  😄 

So you are getting the same results using the "Pro" and "non-Pro" gadgets?  That's odd, but then again, I've never seen a 10Gbit network adapter.  Is there anything unusual about these; i.e., are there two connections or something?  The gadgets are watching a single interface, so it looks like when it's in 10Gbit mode, you are seeing half the performance or something like that.

**Comment by zme-ul** [comment]
I used the PRO and the non-pro, same result

there's a single NIC active, the peak the gadget shows is less than 1/2 of the actual throughput

**Comment by SilverAzide** [comment]
Does Windows task manager show the correct values?  The "non-Pro" gadgets use Rainmeter's Net measures, so they are reading off too.  What happens if you configure the gadget with no adapters (i.e., set the 3 adapter values to blanks)?

**Comment by zme-ul** [comment]
yes, Task Manager shows the same values as the gadget, seems W11 22H2 has issues with correctly monitoring 10gbe interfaces

I left the fields blank in the gadget's settings, no change

**Comment by SilverAzide** [comment]
OK, great!  Thanks for your assistance on this.  I guess at this point we just have to wait for a fix.  22H2 messed up CPU monitoring too; not sure if it is related.

**Comment by SilverAzide** [comment]
Closing this for now; will reopen if needed.
