### ISSUE TITLE
All CPU Meter Bug?

### ISSUE THREAD

**Issue by Alex-Mirov** [SilverAzide/Gadgets#62]
Hello

CPU Clock Speed (single) will show 0 MHz with multicore temperatures,
when disable the multicore temperatures it will show the cpu frequency. 

It's very frustrating! 

Thanks

**Comment by SilverAzide** [comment]
Hm.  That's strange.  It is working fine for me.  There's no relationship between the temps and the CPU clock speed (though there _is_ a relationship between the 3rd-party monitoring utility you are using (if any) and the CPU clock speed).  Are you using HWiNFO or something else?  Did you configure all the core clocks in your HWiNFO.inc settings file?  What version of Windows are you running?

![image](https://user-images.githubusercontent.com/2706567/201497270-2b5476f9-a034-4121-b941-1028daa8cd5d.png)

**Comment by Alex-Mirov** [comment]
Hello

I'm using the latest HWiNFO beta, i didn't config all the core clocks only single speed.

Windows 11 22h2

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SilverAzide** [comment]
Well, there's your problem.  I don't really know what you mean by "only single speed", but configure the clocks for all your CPU cores.  This will most likely result in your sensor indexes changing for everything else, so you'll need to recheck all the settings in your HWiNFO.inc file.

**Comment by Alex-Mirov** [comment]
Hello

I meant the clock speed that below the
processor name, like in the screenshot you've sent.

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SilverAzide** [comment]
Oh, I see what you mean.  There is no one setting for the value shown there.  As I mentioned previously, you will need to configure all your clock sensors.  The value shown depends on this, otherwise you will get zero, as you mentioned.

**Comment by Alex-Mirov** [comment]
Hello

Ok, i will try what you suggested.

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SilverAzide** [comment]
OK!  Let me know how it goes.

**Comment by Alex-Mirov** [comment]
Hello

Thanks for you’re help i’ve managed to make clock speed to show with cores temps, I had to config the HWiNFO index almost entirely.
But it was worth it!

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by SilverAzide** [comment]
Great news!  Glad you got it all working!
