### ISSUE TITLE
How to reduce number of cores shown

### ISSUE THREAD

**Issue by wjsnet** [SilverAzide/Gadgets#65]
I'm new to Gadgets, and can't figure out how to reduce the number of cores shown in the CPU Meter gadget. I have an i7-12700k with only 6 cores (12 virtual) and the gadget shows 20.  Found the TotalCores variable, and the comment not to change (I did try changing it and it broke the gadget).  FYI, saw the open issue on the battery/UPS. I was able to remove the invalid data from the battery gadget and configure HWINFO gadget with the UPS values! Thanks.

**Comment by miquelfire** [comment]
20 (8 performance (16 virtual) and 4 efficient, no HT) is the correct number of cores for that processor. I'm more curious as to where you got that 6/12 number from. Did you go to the BIOS and disabled some cores?

**Comment by SilverAzide** [comment]
Hello @wjsnet,

Welcome to the Gadgets!  @miquelfire is correct, the [i7-12700K](https://www.intel.com/content/www/us/en/products/sku/134594/intel-core-i712700k-processor-25m-cache-up-to-5-00-ghz/specifications.html) CPU has 20 logical cores (8P+4E), so the CPU Meter is working properly.

You can change the CPU Meter to show only the average CPU usage (a single bar) if you want.  To do this, open the Settings and uncheck the option **Show Usage Per Logical Core**.

**Comment by wjsnet** [comment]
Yeah, sorry new computer. When I purchased the CPU, something stuck in my mind it was 4P+2E.  You are right, all is good. Thanks.
