### ISSUE TITLE
Chronometer does not restart event countdown

### ISSUE THREAD

**Issue by Siggi0904** [SilverAzide/Gadgets#67]
Hi,

after 2022-12-31 the new year countdown doesn't restart again.

![grafik](https://user-images.githubusercontent.com/4992106/210614027-ca8b06bf-742a-42e9-96fe-30c458d6ae9a.png)

**Comment by thebezelproject** [comment]
You must modify the event alarm to use 2024.

**Comment by Siggi0904** [comment]
Oh je, me was thanking, new year event will shift automatic.
Changed it and it works.

But cannot deactivate ring tone withe the music sign.
Nothing happens.

**Comment by SilverAzide** [comment]
The "music sign" deactivates the ring tone while the tone is playing.  It's like a mute button; it is not like a on/off button.  If the sound file is short (less than one second) then it won't really have much of an effect in any case.

**Comment by Siggi0904** [comment]
Oh, super. Thanks, for the information.
I'll close it.
