### ISSUE TITLE
request for enhancement

### ISSUE THREAD

**Issue by gurkburk76** [SilverAzide/Gadgets#70]
So i just upgraded to a 13600k and new mb etc, would it be possible to add some sort of panel for chekcing out stuff like mb fans? i don't think there is a sutable panel for that and i don't really think it belongs to the cpu meter panel either. i'm not good enough to hack something together myself :)

**Comment by SilverAzide** [comment]
Hello!  At this point, you could use the GPU Meter to monitor additional fans.  The GPU Meter can show up to 4 fans and 6 additional optional sensors.

Other than that, I do intend to create a new HWiNFO gadget that would be able to monitor whatever sensors you want.  This is issue #64, where someone is asking for a gadget that can report UPS stats.  Check it out, you can try the HWiNFO Monitor in the Gadgets Additions pack that might be one solution until I can get around to doing my own.

**Comment by SilverAzide** [comment]
Added new HWiNFO gadget to allow monitoring any available sensors; will be in next release.
