### ISSUE TITLE
[Feature Req] Add ability to manually specify total VRAM

### ISSUE THREAD

**Issue by candre23** [SilverAzide/Gadgets#71]
My GPU (tesla P40) does not output MemoryUsage as a percent.  It does provide MemoryAlloc.  If there were an option to manually specify the total VRAM in the config file, the meter could easily calculate the % used and % free.

**Comment by SilverAzide** [comment]
Hello!  Actually, there is an option for that.  I'm not familiar with the Tesla GPUs, but AMD and other GPU are similar in that they don't provide a percentage usage either.

Open the HWiNFO.ini file and look for the option `GPU0_MemoryTotal`. Change the default value of `0` to the memory on your video card in megabytes (e.g., 24GB would be `24576`).

**Comment by candre23** [comment]
Thank you.  I don't know how I missed that the first three times I went looking for a way to make the memory report properly.  My bad.
