### ISSUE TITLE
Unable to set up CPU usage and Temps

### ISSUE THREAD

**Issue by Volern** [SilverAzide/Gadgets#73]
I am unable to get these settings going. I have set the the GPU stuff up and its all good, but the CPU stuff just refuses to work and I am unsure what I have done wrong. Can anyone see whats wrong here? The last image was edited to only show what is populated, every entry not shown there is blank.

![image](https://github.com/SilverAzide/Gadgets/assets/13373330/2e73d5c2-01b3-4096-91f5-aef9c85e1b64)
![image](https://github.com/SilverAzide/Gadgets/assets/13373330/f0842c4b-ac14-4646-9dd5-371ec9e172d9)
![image](https://github.com/SilverAzide/Gadgets/assets/13373330/c3833ff1-1876-49fa-af09-93869af1c679)
![image](https://github.com/SilverAzide/Gadgets/assets/13373330/183600e6-7099-467b-96f4-39df31788778)

**Comment by SilverAzide** [comment]
Hello!  Sorry you are having issues!  I see you are not using the latest version, so please try installing that first.  You might want to do a clean install (i.e., delete the `Gadgets` folder and any copy in the `@Backup` folder) to prevent Rainmeter from carrying over your skin settings, which appear to be corrupted somehow.

The most obvious issue I see is not anything to do with HWiNFO.  The first image you posted of the CPU skin is showing "Core -nan", which is something I've never seen before.  The skin attempts to configure itself automatically, but for some reason it is crashing when numbering your cores.  ("-nan" is "negative not-a-number", like a divide by zero.)  My guess is that it is seeing zero cores, which means something basic is failing.

Open the Rainmeter log by right-clicking the Rainmeter icon in the notification area and selecting "About", and select the "Log" tab. Look for errors in the log.  Also, on the Plugins tab, make sure the ActiveNet plugin is installed.  The skin will not function without it.  You can also view the log file by right-clicking the Rainmeter icon and selecting Manage > Settings tab, and clicking the "Show log file" button.  Post that file here if you cannot see the problem.

**Comment by Volern** [comment]
Thanks for that. I have no idea how I managed to use an old version as I just reinstalled windows and had to download it again but getting the new version fixed it. I found that the refresh skin option did nothing though and had to restart rainmeter to update the changes but it all worked out now. Thanks.
