### ISSUE TITLE
Network meter options not showing Scale size

### ISSUE THREAD

**Issue by liam-maps** [SilverAzide/Gadgets#75]
Hi!
Congrats on your gadgets! I'm replacing the now old "modern gadgets" with yours.
I'm used to scale the gadgets at 1.25, but in the case of Network meter there's no option when clicking the wrench icon.
I've managed to set it through \Documents\Rainmeter\Skins\Gadgets\@Resources\NetworkVariables.inc, but I think I'd be great having it under the options menu like the other gadgets.
Thanks for your work!

**Comment by SilverAzide** [comment]
Hello!  Glad you are enjoying the Gadgets!
The scaling option is definitely there, you might want to check it again.  It's in the same relative place in all Settings skins.

![Screenshot 2023-07-01 144208](https://github.com/SilverAzide/Gadgets/assets/2706567/79a9dc95-e711-4d38-9bb9-7f00e8e4881d)
