### ISSUE TITLE
CPU meter

### ISSUE THREAD

**Issue by bandaid** [SilverAzide/Gadgets#77]
Possible to make all CPUs the same color until they reach a certain usage threshold and then change color? Multicolor graph is useless with 32+ cores.

**Comment by SilverAzide** [comment]
There's two different items here, one is the bars and another is the graph.  The TLDR version is yes, it is possible, but it will not be something I'll be implementing in the Gadgets.

One very simple thing you can do to the bars is implement a gradient bar effect similar to your suggestion.  Open the CpuMain.inc file and look for the following style meter near to the top of the file:
```ini
[StyleBar]
BarOrientation=Horizontal
; uncomment if you want all bars to have a gradient color appearance
;BarImage=#@#BarGradient.png
```
As shown, uncomment the `BarImage` line.  All the bars will have a temperature gradient effect.  You can alter the image to change the appearance.  It is also possible to do the gradient with code (not an image), which would give you fine-grained control over the appearance.

Not really sure I understand what you are asking about the graph.  If you don't like all the lines, you can already turn them off, or just show a single line for the whole CPU.  If you want the lines to be drawn like a gradient similar to the bars, that is possible as well, you would just alter the way the graph is drawn.  You'd need to use a Container meter along with the graph to get an effect something like this:
![](https://forum.rainmeter.net/download/file.php?id=24341)

Containers are pretty cool, you can read about them in the Rainmeter manual [here](https://docs.rainmeter.net/manual/meters/general-options/container/).  It would not be too difficult to implement.

**Comment by SilverAzide** [comment]
I'll close this issue for now, but if you want help implementing this yourself, let me know.
