### ISSUE TITLE
Feature request: UT total instead of Logon

### ISSUE THREAD

**Issue by Pookson** [SilverAzide/Gadgets#81]
Hi! 
Thank you for your work! I've been using addgadgets for ages and finally made a decision to upgrade)
But I'm missing UT total counter in chronometer. Is it possible to add an option to show it instead of logon timer?

**Comment by SilverAzide** [comment]
Hello!  Glad you like the Gadgets!

The chronometer has session uptime and logon time.  Is there another counter?  I was under the impression that these options were the same two used in the addgadgets clock, but with lightly different names ("UT Current" = "Logon" and "UT Total" = "Uptime").  Was "UT Total" cumulative?

**Comment by Pookson** [comment]
> Was "UT Total" cumulative?

Yes, exactly.
![1](https://github.com/SilverAzide/Gadgets/assets/126565938/2fa6084b-23a9-441c-adfd-16d54fbf94ce)

**Comment by SilverAzide** [comment]
Oh, interesting!  I didn't realize that.  Well, as far as I can tell, there is nothing in Windows that I can find that keeps track of total cumulative uptime.  I assume then that the gadget itself kept track of how long it was running, which is more like "uptime of the gadget" rather than of the PC.  There is a way to get the date the OS was installed and calculate how long that's been, but that's not the same thing as uptime.

Since there's no method that is built into Windows or Rainmeter to find total cumulative uptime, I'm tempted to not look too much further into this option.  Trying to track Rainmeter/skin cumulative uptime could be problematic, given skin refreshes and so forth that would restart the clock.  I'll think about it though, it could be an interesting experiment try to get working.

**Comment by Pookson** [comment]
Thank you for consideration!

**Comment by SilverAzide** [comment]
> Thank you for consideration!

I think I have this working.  If you want to test a beta version, let me know.

**Comment by Pookson** [comment]
I would gladly do so! Thank You!

**Comment by SilverAzide** [comment]
OK, great!

First, open your `ChronometerVariables.inc` file and add the following two variables:
```ini
HideTotalUptime=0
TotalUptime=0
```
For testing purposes, you can set the TotalUptime value to some large value (this is the total cumulative uptime value in seconds).

Next, overwrite your `Digital Clock.ini` skin file with the following version in this zip:
[Digital Clock.zip](https://github.com/SilverAzide/Gadgets/files/12775484/Digital.Clock.zip)

Refresh your clock and you should see something like:
![image](https://github.com/SilverAzide/Gadgets/assets/2706567/06ba2f58-7e17-42e4-9369-3a3e6d5a65df)

**Comment by SilverAzide** [comment]
Just a reminder; the "UT Total" value is the uptime of the **skin**, not your PC.  There is no way in Windows to obtain the actual cumulative uptime of your machine.  So, if the skin is not running, the clock stops.  Also, the skin updates the running total at 1 minute intervals, so you may notice write activity.  If you refresh the skin (or Rainmeter), you may lose 0-59 seconds of uptime.  Closing/unloading the skin normally will flush the uptime to disk.

**Comment by Pookson** [comment]
I am so grateful that you are actually doing something and investing your time in this minor tweaks. Again, thank you! 

P.S.
I think network meter just kept an .ini file to count each MB of traffic to display ttl downlaod\upload. Is it possible to do the same for the clock for our purpose? I'm not a programmer, so bare with me if it's stupid,

**Comment by Pookson** [comment]
![123](https://github.com/SilverAzide/Gadgets/assets/126565938/f7771dcc-edfc-439f-8db2-5e18dc3abfe8)
![Screenshot_2](https://github.com/SilverAzide/Gadgets/assets/126565938/ff476673-ddac-4698-ab3e-97ce476a514c)

Works just fine! Fixed my retro+ocd vibe) If anything weird happens, gonna report back. Should I close this issue?

**Comment by SilverAzide** [comment]
> P.S. I think network meter just kept an .ini file to count each MB of traffic to display ttl downlaod\upload. Is it possible to do the same for the clock for our purpose? I'm not a programmer, so bare with me if it's stupid,

Yes, Rainmeter has that feature built in, but there's nothing similar for uptime.  The skin itself will attempt to track the uptime and store this value for you, but it's not a bullet-proof approach.

**Comment by SilverAzide** [comment]
> Works just fine! Fixed my retro+ocd vibe) If anything weird happens, gonna report back. Should I close this issue?

Excellent!  I'll close the issue, but if you run into any problems, feel free to reopen and report them.

**Comment by SilverAzide** [comment]
Enhancement will be available in the next release of the Gadgets.
