### ISSUE TITLE
Display name in HWiNFO Meter

### ISSUE THREAD

**Issue by night-herons** [SilverAzide/Gadgets#82]
The addition of a panel that can display HWiNFO sensor data would be very nice.

However, it would be nice to be able to manually set the item names.
For example, the SPD Hub temperature is a little confusing because it has a different target but the same display name.
(e.g. Sensor1_Label="MemSlot1 Temp")
Another point is that it would be good to be able to adjust the number of decimal places, since multiple decimal places are not lined up well.
(Perhaps it could be done by using the Setting panel to align the number of digits for the entire value.)

![image](https://github.com/SilverAzide/Gadgets/assets/28802007/9a364ca3-ab54-42e4-b962-7792357ec8fa)

**Comment by SilverAzide** [comment]
Hello!  Glad you are finding this useful!

The skin is displaying data directly from HWiNFO, so the number of decimals and sensor names are coming from there.  If you want to change the names, you can use HWiNFO itself.  Open the sensor status screen in HWiNFO, find the sensor you want, and right-click and select Rename (or press F2) to rename to whatever you like.

As far as the decimals, those are coming from HWiNFO as well, and there does not appear to be a way to change this.  Please note that the skin is retrieving these values as **text** (including the units of measure), not numbers, so the Rainmeter functions to control decimals places does not work.

**Comment by night-herons** [comment]
Thank you for answering.
I didn't think that HWiNFO was the cause.
Thanks to this, I was able to change the display name and number of digits, both from the sensor settings.
![スクリーンショット 2023-10-09 175909](https://github.com/SilverAzide/Gadgets/assets/28802007/bdd96061-4f37-4ba4-96c1-eae6867b6b8e)

At that time, I noticed that "GPU 消費電力" was displayed as "消費電力" on HWiNFO Meter.
" GPU 消費電力" with a space at the beginning becomes " GPU 消費電力",
"GPU消費電力" without spaces was displayed as "GPU消費電力".
The same thing happened with the original "GPU Power".
It's not a big problem since you just need to remove the space, but I'll let you know just in case.
![スクリーンショット 2023-10-09 174910](https://github.com/SilverAzide/Gadgets/assets/28802007/22f559eb-c026-4fcf-9573-64e967d99769)
![スクリーンショット 2023-10-09 174936](https://github.com/SilverAzide/Gadgets/assets/28802007/8679463a-15fb-4f28-9ede-a3eb5050ad0a)
![スクリーンショット 2023-10-09 174958](https://github.com/SilverAzide/Gadgets/assets/28802007/5e15fd86-9207-479f-95a8-598bebf22fd5)
![スクリーンショット 2023-10-09 175033](https://github.com/SilverAzide/Gadgets/assets/28802007/996eda24-9402-4c71-9723-358069d59bcf)

**Comment by SilverAzide** [comment]
OHhhhhh... Now I understand what you are asking.  Sorry about that!

Yes, the HWiNFO Meter is automatically removing and leading "CPU" and "GPU" text from the labels.  I find this text annoying since it is repetitive, so I removed it.  See the following code in the skin:
```ini
Substitute="^CPU ":"","^GPU ":"","^0$":"???"
```
Look for the above lines and remove the `"^CPU ":"","^GPU ":"",` text (you can do a global search-and-replace).  This will make the gadget show exactly what is in HWiNFO.  When you are done, the lines should read:
```ini
Substitute="^0$":"???"
```

**Comment by night-herons** [comment]
Thank you for answering.
It no longer disappears from the display.
![image](https://github.com/SilverAzide/Gadgets/assets/28802007/990268c0-5a12-4e4c-9acd-6247824371f8)
