### ISSUE TITLE
GPU meter doesn't work

### ISSUE THREAD

**Issue by huggywuggybest03** [SilverAzide/Gadgets#85]
I enabled the GPU meter on Rainmeter, and I followed the instructions to use the GPU meter but it isn't working. I tried everything I could.

GPU stats:
Graphics Card: ASUS HD7770
![how](https://github.com/SilverAzide/Gadgets/assets/135007348/28829a0a-640c-4564-8728-273d1c984682)

Graphics Chipset: AMD Radeon HD 7770/R7 250X
GPU Codename: CAPE VERDE XT
Graphics Card Bus: PCIe v3.0 x16 (8.0 GT/s) @ x16 (2.5 GT/s)

Can anyone help here?

**Comment by SilverAzide** [comment]
Sorry you are running into issues.  Looks like you might have missed a few configuration items.  First, be sure you configured the correct GPU Meter.  HWiNFO might be seeing your on-board GPU in addition to your dedicated card, in which case your dedicated card might be GPU 1 instead of GPU 0.  Check to see which of the 3 sets of GPU variables you configured.  To keep things simple, configure GPU 0 variables with whatever HWiNFO reports for your card and use the GPU 0 skin.

The next thing to check is your sensor configuration.  Make sure you have correctly configured the GPU temperature sensor.  If the skin does not see a temperature, it thinks the configuration is missing or bad.

Review your sensor index list and your HWiNFO.inc variables file.  If you can't figure it out, attach them to your post and I'll take a look.

**Comment by huggywuggybest03** [comment]
i did the gpu 0 and im confused, here are the images
![image](https://github.com/SilverAzide/Gadgets/assets/135007348/78984188-285c-4f6f-af68-bb399a0f9839)
![image](https://github.com/SilverAzide/Gadgets/assets/135007348/4ee1e787-414b-4c13-8450-624147cceab1)
![image](https://github.com/SilverAzide/Gadgets/assets/135007348/1b9ddf60-dad6-496f-9bf6-d1ebf5ff3337)

**Comment by SilverAzide** [comment]
You indicated you followed the instructions, but it looks like you only configured HWiNFO.  So you've only completed half the job; you have to tell the Gadgets what the **sensor indexes** are.  You also didn't configure the GPU temperature sensor either (is it "thermal diode"?).  As I mentioned above, the GPU Meter won't know HWiNFO is running if there is no temp sensor.

Read [this wiki article](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Configure-HWiNFO) and resume at step 9, you've added most of the needed sensors, but you are missing an item or two.  Read all the way to the end, especially the "What's Next" section.  You don't appear to have done the last and most important part.  If you have completed this and are still having issues, then attach the index list and variables files (paperclip icon).

P.S.:  If you want to use the CPU Meter, you ought to configure that now too.  If you don't and want to use it later, when you add the sensors it will change all the index numbers for your GPU Meter, and you'll need to adjust the configuration again.

**Comment by huggywuggybest03** [comment]
im confused
![image](https://github.com/SilverAzide/Gadgets/assets/135007348/c7b66895-a060-4e46-af60-ee659692c54b)
![image](https://github.com/SilverAzide/Gadgets/assets/135007348/bdc18c94-d9d2-4a15-9828-969bdfa49536)
i did some more stuff too and i followed the steps but im confused on the wiki article for the 4th one

**Comment by huggywuggybest03** [comment]
my cpu meter works fine too

**Comment by SilverAzide** [comment]
> my cpu meter works fine too

It should, because the CPU Meter does not require HWiNFO to work.  The GPU Meter can't function with HWiNFO.

**Comment by SilverAzide** [comment]
> im confused 
> i did some more stuff too and i followed the steps but im confused on the wiki article for the 4th one

Which "4th one" are you referring to?  Opening the variables file in Notepad?

From your screenshot, I see you have selected all the sensors needed by the GPU Meter, plus a few extras.  Now all that is left for you to do is actually configure the GPU Meter.  So far, all you have done is configure **HWiNFO**.

**Comment by huggywuggybest03** [comment]
the 4th one which says "Click the Notepad icon to display the HWiNFO configuration file, and carefully follow the instructions in the file to assign the indexes to the appropriate variables for your various devices.", it says no instructions in the configuration file.

**Comment by SilverAzide** [comment]
> it says no instructions in the configuration file.

What says this?  I'm very sorry, I'm not following, you need to very clear what you are seeing.  There is nothing in this suite which says "no instructions in the configuration file".  This really makes no sense.  Can you please open the `Gadgets\@Resources\HWiNFO.inc` file and follow the instructions to fill it out?  Is this file missing?

**Comment by huggywuggybest03** [comment]
the HWiNFO.inc file isn't missing, I opened the indexes thing from the maintenance wrench and it just pops up with configurations, is that better? I'm just confused.

**Comment by SilverAzide** [comment]
OK... I'm not sure how to make the instructions any clearer.  How about this:

Click the wrench:
![image](https://github.com/SilverAzide/Gadgets/assets/2706567/a3a44d61-cd53-4321-85e7-09e3cb0c14fe)

Click the HWiNFO icon to get your sensor index list:
![image](https://github.com/SilverAzide/Gadgets/assets/2706567/23699bf8-2b99-434a-8e2c-f7da9c5770c4)

Click the Notepad icon to open the HWiNFO.inc file:
![image](https://github.com/SilverAzide/Gadgets/assets/2706567/f083e240-b032-4540-afd5-4dc780efc8a5)

READ THE ENTIRE HWINFO.INC FILE FROM TOP TO BOTTOM

Per the instructions in the file and on the wiki pages, enter your sensor indexes against the appropriate variables.
![image](https://github.com/SilverAzide/Gadgets/assets/2706567/42fdd60b-f0d8-4f76-bd3c-7d2e48e38846)

Does this help?

**Comment by SilverAzide** [comment]
Closed. No response
