### ISSUE TITLE
CPU meter & drives meter issue

### ISSUE THREAD

**Issue by rakantoh** [SilverAzide/Gadgets#86]
i did a fresh install of my OS, and since i installed rainmeter and gadgets, the drives meter and cpu meter doesn't works, the drives meter shows all drives in 100%, and cpu meter shows 0 processor activity and no ram usage/total/available. All hwinfo soft and hwinfo.inc file are correctly configured.

Wireless meter and gpu meter works normally.

![imagen_2023-11-07_211057367](https://github.com/SilverAzide/Gadgets/assets/59809634/67a7861a-1592-46ca-bf11-61634b5f898c)

**Comment by SilverAzide** [comment]
Yes, this is very common!  Your Gadgets are working, and telling you there is a problem with your PC. 😃 It happens frequently with OS and hardware changes, so it is nothing you did.

Your symptoms are a guaranteed indicator of a corrupted Performance Counters database.  The good news is it's a simple fix.  Check out this wiki article:

[HOW TO: Fix your Performance Counters database](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Fix-your-Performance-Counters-database#how-to-fix-your-performance-counters-database)
