### ISSUE TITLE
Core usage stopped working

### ISSUE THREAD

**Issue by screwyluie** [SilverAzide/Gadgets#88]
Recently the core usage stopped working, not sure why, never been a problem before. Everything else works fine just cpu core usage bars and graph show nothing.
![JvhuP9HUmx](https://github.com/SilverAzide/Gadgets/assets/3519787/f75a6b25-d34b-4b9e-b8c7-17aa6821a6de)

**Comment by SilverAzide** [comment]
Sorry you are having issues.  Try this:

[HOW TO: Fix your Performance Counters database](https://github.com/SilverAzide/Gadgets/wiki/HOW-TO-Fix-your-Performance-Counters-database)

**Comment by screwyluie** [comment]
That did not work. I would assume it's getting that info from HWInfo not windows though? 
![image](https://github.com/SilverAzide/Gadgets/assets/3519787/ac85aa90-bb4d-43c9-a885-7ea3ae4cf2d7)

**Comment by SilverAzide** [comment]
That didn't work???  Huh, something must be really wrong with your setup.  (And no, HWiNFO is not used for this, the info is coming from Windows performance counters.)

What version of Windows are you using?  If you are using Windows 7, it could be something related to that.  Another thing to try is to open the Settings and check the option "Use Legacy Mode".  Does that change anything?

P.S.:  Sorry for the late response.

**Comment by screwyluie** [comment]
to answer the question, Windows 10.

Thank you for the information, this let me do some troubleshooting and narrowed down the issue to rainmeter and not your skin. Got it working again.
