### ISSUE TITLE
Suggestion: HWMeter custom lables

### ISSUE THREAD

**Issue by MADxHAWK** [SilverAzide/Gadgets#90]
It would be nice if you could add a opportunity to add custom labels to the HWMeter Gadget. 
Im using it to monitor the temperature of my SSDs and another one for the CPU and GPU power. 
using the HW_Info lable for the value is not realy straight forward for my SSDs it looks like
Temperature 1: 53°C
Temperature 1: 55°C
Temperature 1: 49°C

So custom Lables would be a very nice feature 

Merry Christmas / Happy Hollydays
MADxHAWK

**Comment by SilverAzide** [comment]
Glad you are enjoying the Gadgets!

I did think about this, but I decided to not implement anything until I got more feedback.  I agree with you, I see similar things.  However, you are in luck, as there is another way to handle this situation.

The gadget is pulling these descriptions from HWiNFO.  You can rename them in HWiNFO directly to give them better names... anything you want, really.

To do this, on the Sensors screen you can right-click any sensor and select the Rename option and give it something more descriptive than the default.  Does this work for you?

**Comment by MADxHAWK** [comment]
Hi, 

thanks for the reply, due to the hollydays i couldnt reply sooner.
Yes this works for me, thanks a lot for that hint.

Greetings 
MADxHAWK
