### ISSUE TITLE
Migrating the Total Usage of Upload and Download from Network Meter by addgadgets.com

### ISSUE THREAD

**Issue by rockychf** [SilverAzide/Gadgets#91]
I was using the Network Meter v9.6 by addgadgets.com before and now I changed to use Rainmeter + Gadgets (Network Meter), may I know how can I modified the Total Usage in Network Meter of Gadgets so that I can migrate the Total Usage of Upload and Download data from the old Network Meter I was using?

**Comment by SilverAzide** [comment]
P.S.:  Just a reminder that the Network Meter (both Pro and non-Pro) show the sum total of all configured adapters in the "Total".  For example, if you configure both Ethernet and WiFi adapters, you'll see the total is the sum of both adapters.  You can temporarily change the configuration to a single adapter to test that your transferred values are being shown correctly.  If you leave all the adapter settings blank, then the skin will only show data for the active adapter (or what Rainmeter decides is the active one).
