### ISSUE TITLE
weather timestamp issue?

### ISSUE THREAD

**Issue by wulfie66** [SilverAzide/Gadgets#99]
So I've updated to the latest set of widgets and all is great except the weather, I get the following error in the log
Invalid TimeStampFormat: %Y-%m-%dT%H:%M:%S (Gadgets\Weather Meter\Weather Meter.ini - [MeasureCurrentObservationTime])
is there any fix for this?  I've already tried deleting my internet cache to no avail :(

**Comment by LeBlackMeow** [comment]
I'm having the same issue. Weather gadget no longer show forecast.

**Comment by wulfie66** [comment]
> I'm having the same issue. Weather gadget no longer show forecast.

https://forum.rainmeter.net/search.php?author_id=33554&sr=posts

**Comment by LeBlackMeow** [comment]
> > I'm having the same issue. Weather gadget no longer show forecast.
> 
> https://forum.rainmeter.net/search.php?author_id=33554&sr=posts

Thanks, changing manually the API fixed it.

**Comment by feathered-arch** [comment]
> > > I'm having the same issue. Weather gadget no longer show forecast.
> > 
> > 
> > https://forum.rainmeter.net/search.php?author_id=33554&sr=posts
> 
> Thanks, changing manually the API fixed it.

Changing it how? Would you like to share with the rest of the class, perhaps?

**Comment by feathered-arch** [comment]
> > > I'm having the same issue. Weather gadget no longer show forecast.
> > 
> > 
> > https://forum.rainmeter.net/search.php?author_id=33554&sr=posts
> 
> Thanks, changing manually the API fixed it.

It's polite to leave the solution for others to easily find. Letting us all know that you fixed it yourself isn't helpful without detail. 

##WORKAROUND

Locate this file:
.\Rainmeter\Skins\Gadgets\@Resources\WeatherComJSONVariables.inc

At line 37, below "; Don't change any below here.", change it to:

APIKey=71f92ea9dd2f4790b92ea9dd2f779061

Save, and refresh the widget. It should now work.

**Comment by SilverAzide** [comment]
Thanks everyone!  Patch will be coming out shortly!
